export class UserActivityDetailEntity {
    UserActivity_Id: number;
    Session_Id: number;
    Screen_Id: number;
    Time: string;
    Activity_Id: number;
    Comments: string;
}
export enum Screens {
  Dashboard = 1,
  CompanyMaster = 2,
  FacilityMaster = 3,
  NurseStationMaster = 4,
  FloorMaster = 5,
  WingMaster = 6,
  RoomMaster = 7,
  BedMaster = 8,
  Users = 10,
  RoleMaster = 11,
  RoleConfig = 12,
  UserRoleConfig = 12,
  HLSegmentFieldsConfig = 14,
  FTPConfiguration = 15,
  AllergyMaster = 16,
  ICD10Master = 17,
  CompanyBedConfig = 9,
  FrequencyMapping = 18,
  Inbound = 19,
  Outbound = 20,
  ResidentGrid = 21,
  DemographicInformation = 22,
  AdmitVisitInfo = 23,
  ResidentGridOrders = 24,
  Medication = 25,
  Allergies = 26,
  Diagnosis = 27,
  Integrations = 28,
  PhysicianDetails = 28,
  Orders = 29,
  AdminApproval = 30,
  DocumentManager = 31,
  EMAR = 32,
  PRNDocumentation = 33,
  SeventyTwoHourChecks = 34,
  ControlSubstance = 35,
  DrControlSubstance = 36,
  Vitals = 37,
  WeightLog = 38,
  FoodIntake = 39,
  NurseNotes = 40,
  Behaviour = 41,
  Census = 42,
  SeventyTwoHoursDashboard = 43,
  PRNDashboard = 44,
  OrderDashboard = 45,
  BarcodeDashboard = 46,
  BiometericDashboard = 47,
  OrderControlSubstanceDashboard = 48,
  OrderwithFavouritesDashboard = 49,
  OrderSignoffDashboard = 50,
  OrderHoldDashboard = 51,
  RefusedByResidentDashboard = 52,
  OrderChangeDashboard = 53,
  ScanningBypassDashboard = 54,
  DestructionDashboard = 55,
  FloorStockDashboard = 56,
  CheckInMedsReport = 57,
  PsychiatricDashboard = 58,
  NurseNotesDashboard = 59,
  PrescriberNotesDashboard = 60,
  HL7InboundDashboard = 61,
  HL7OutboundErrorDashboard = 62,
  MARDashboard = 63,
  Mailbox = 64,
  UserActivityDashboard = 65,
  ColorPicker = 1059,
  Stock = 1060,
  Ekit = 2070,
  AcknowledgeOrders = 1063,
  EkitDashboard = 1064,
  StockDashboard = 1065,
  DrFirstFiles = 1066,
  AdminUsersReport = 1067,
  SetupConfigReport = 1068,
  RefillReport = 2067,
  ADTFieldsDisplayConfig = 2071,
  CompanyBedHierarchy = 2077,
  CertificationOrders = 3077,
  CertifiedOrdersReport = 3078,
  CompanyConfiguration = 1069,
  NewResident = 2069,
  Transfer = 2072,
  Discharge = 2073,
  CheckInMeds = 2074,
  DocumentAdminReport = 2076,
  DocumentAdministeredOrders = 2075,
  Alerts = 1062,
  MeasurementandOtherChecksMaster = 3079,
  EkitMedsCheckIn = 3081,
  MedicationExpirationDateReport = 3080,
  EKitMedsExpirationDateReport = 3082,
  RefillRejectMailConfig = 3083,
  CPOE = 3084,
  ResidentProfileCertificationOrders = 3085,
  ResidentProfileCertifiedOrdersReport = 3086,
  MailConfig = 3087,
  PharmacyDetails=3088,

}

export enum Activity {
    View = 1,
    Save = 2,
    Edit = 3,
    PDF = 4,
    Excel = 5,
    Search = 6,
}
export enum DefaultScreen {
    d1 = '/home/dashboard',
    d2 = '/home/companymaster',
    d3 = '/home/facilitymaster',
    d4 = '/home/nursestation',
    d5 = '/home/floor',
    d6 = '/home/wing',
    d7 = '/home/room',
    d8 = '/home/bed',
    d9 = '/home/emaruser',
    d10 = '/home/role',
    d11 = '/home/roleconfig',
    d12 = '/home/usrfacroleconfig',
    d13 = '/home/hlsegment',
    d14 = '/home/fteconfig',
    d15 = '/home/allergymaster',
    d16 = '/home/icdmaster',
    d17 = '/home/companybedconfig',
    d18 = '/home/frequencymapping',
    d19 = '/home/inbound',
    d20 = '/home/outbound',
    d21 = '/home/residentgrid',
    d28 = '/home/integrations',
    d29 = '/home/ordergrid',
    d30 = '/home/adminapproval',
    d31 = '/home/documentmanager',
    d32 = '/home/administration',
    d33 = 'home/prndocumentation',
    d34 = '/home/72hourchecks',
    d35 = '/home/controlsubstance',
    d36 = '/home/DrControlSubstance',
    d37 = '/home/vitals',
    d38 = '/home/weightlog',
    d39 = '/home/foodintake',
    d40 = '/home/nursenotes',
    d41 = '/home/behaviour',
    d42 = 'home/censusdashboard',
    d43 = '/home/seventytwodr',
    d44 = '/home/prndr',
    d45 = '/home/orderdr',
    d46 = '/home/barcodedr',
    d47 = '/home/biometericdr',
    d48 = '/home/ordercontrolsubstancedr',
    d49 = '/home/orderwithfavouritiesdr',
    d50 = '/home/ordersignoffdr',
    d51 = '/home/orderholddr',
    d52 = '/home/refusedbyresdr',
    d53 = '/home/orderchangedr',
    d54 = '/home/scanningbypassdr',
    d55 = '/home/destructiondr',
    d56 = '/home/floorstockdr',
    d57 = '/home/pharmacymedsdr',
    d58 = '/home/psychiatricdr',
    d59 = 'home/nursenotesdr',
    d60 = '/home/prescribernotesdr',
    d61 = '/home/hlseveninbounddr',
    d62 = '/home/hlsevenoutbounderrordr',
    d63 = '/home/mardr',
    d64 = '/home/mailbox',
    d65 = '/home/useractivitydr',
    d1059 = '/home/colorpicker',
    d1060 = 'home/stock',
    d1063 = 'home/acknowledgeorders',
    d1062 = 'home/alerts',
    d2068 = 'home/physciandetails',
    d1064 = 'home/ekitdr',
    d1065 = 'home/stockdr',
    d1066 = 'home/drfirstfiles',
    d2067 = 'home/refilldr',
    d1067 = 'home/adminusersdr',
    d1069 = 'home/companyconfiguration',
    d1068 = 'home/setupconfigdr',
    d2072 = 'home/outboundhlsegmentfile',
    d2078 = 'home/companytobedmapping',
    d3077 = 'home/certificationorders',
    d3078 = 'home/certifiedordersdr',
    d3080 = 'home/pharmacymedsexpdr',
    d3082 = 'home/ekitmedsexpdr',
    d3083 = 'home/refillrejectmailconfig',
    d3084 = 'home/ordergridcpoe',
    d3085 = 'home/profilecertificationorders',
    d3086 = 'home/profilecertifiedordersdr',
    d3087 = 'home/MailConfig',


}
export enum OutboundEvents {
    TransferPatient = 9,
    DischargeEndVisit = 10,
    UpdatePatientInformation = 11,
    PatientGoesOnALeaveOfAbsence = 12,
    PatientReturnsFromALeaveOfAbsence = 13,
    OrderMessage = 14,
}
export enum OutboundHlEvents {
    PIDForUpdatePatientInformation = 11,
    PV1ForTransferaPatient = 9,
    PV1ForDischargeaPatient = 10,
    PIDForNewAdmission = 11,
    PV1ForNewAdmission = 11,
    PV1ForUpdatePatientInformation = 15
}