//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityMaster()
        {
            this.UserActivityDetails = new HashSet<UserActivityDetail>();
        }
    
        public int Activity_Id { get; set; }
        public string Activity_Desc { get; set; }
        public Nullable<int> Activity_Status { get; set; }
        public Nullable<int> Activity_CreatedBy { get; set; }
        public Nullable<System.DateTime> Activity_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserActivityDetail> UserActivityDetails { get; set; }
    }
}
