//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertText
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlertText()
        {
            this.AlertStatus = new HashSet<AlertStatu>();
        }
    
        public long AlertText_Id { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> AlertText_Status { get; set; }
        public Nullable<System.DateTime> AlertText_CreatedOn { get; set; }
        public Nullable<long> File_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertStatu> AlertStatus { get; set; }
        public virtual AlertType AlertType { get; set; }
        public virtual Demographic Demographic { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
