//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertStatu
    {
        public long Alert_Id { get; set; }
        public Nullable<int> user_Id { get; set; }
        public Nullable<long> AlertText_Id { get; set; }
        public Nullable<int> Read_Flag { get; set; }
        public Nullable<int> Favourite_Flag { get; set; }
        public System.DateTime Alert_CreatedDate { get; set; }
    
        public virtual AlertText AlertText { get; set; }
        public virtual User User { get; set; }
    }
}
