//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllergyTypeCode
    {
        public int AllergyType_Id { get; set; }
        public string AllergyType_Code { get; set; }
        public string AllergyType_Desc { get; set; }
        public int AllergyType_Status { get; set; }
        public Nullable<int> AllergyType_CreatedBy { get; set; }
        public System.DateTime AllergyType_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
