//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllergyInfoMaster
    {
        public int Allergy_Id { get; set; }
        public Nullable<int> AllergyTypeMaster_Id { get; set; }
        public string AllergyDesc_Id { get; set; }
        public string AllergyDesc { get; set; }
        public int Allergy_Status { get; set; }
        public Nullable<int> Allergy_CreatedBy { get; set; }
        public System.DateTime Allergy_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
