//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AncillaryDetail
    {
        public int PAnc_Id { get; set; }
        public int POrder_Id { get; set; }
        public string LiteralOrderCode { get; set; }
        public string LiteralOrderDesc { get; set; }
        public string MAROrderCatSeq { get; set; }
        public string POOrderCatSeq { get; set; }
        public string TAROrderCatSeq { get; set; }
        public string Filler { get; set; }
        public string IncludeOnMAR { get; set; }
        public string IncludeOnPO { get; set; }
        public string IncludeOnTAR { get; set; }
        public string RawAdministrationTimes { get; set; }
        public int PAnc_Status { get; set; }
        public Nullable<int> PAnc_CreatedBy { get; set; }
        public System.DateTime PAnc_CreatedDate { get; set; }
        public Nullable<int> PAncOutBoundFileStatus { get; set; }
        public Nullable<int> PAncOutBoundApproval { get; set; }
        public Nullable<int> PAncOutBoundApprovalBy { get; set; }
        public Nullable<System.DateTime> PAncOutBoundApprovalOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual CommonOrderInfo CommonOrderInfo { get; set; }
    }
}
