//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiIntegration
    {
        public int Integration_Id { get; set; }
        public Nullable<int> Integration_TypeId { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string ApiPath { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Integration_Status { get; set; }
        public Nullable<int> Integration_CreatedBy { get; set; }
        public System.DateTime Integration_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
