//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalRefill
    {
        public long Refill_Id { get; set; }
        public Nullable<int> Porder_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public string NumberOfRefillsRemaining { get; set; }
        public Nullable<int> Refill_Status { get; set; }
        public Nullable<int> Refill_CreatedBy { get; set; }
        public Nullable<System.DateTime> Refill_CreatedDate { get; set; }
        public Nullable<int> POOutBoundFileStatus { get; set; }
        public Nullable<int> POOutBoundApproval { get; set; }
        public Nullable<int> POOutBoundApprovalBy { get; set; }
        public Nullable<System.DateTime> POOutBoundApprovalOn { get; set; }
        public Nullable<int> File_Id { get; set; }
    
        public virtual OutBoundFileInformation OutBoundFileInformation { get; set; }
    }
}
