//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalOrder2
    {
        public long PApprovalOrder_Id { get; set; }
        public Nullable<int> Porder_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> OrderingPhysicianID { get; set; }
        public string OrderControl { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> OrderEffectiveDate { get; set; }
        public Nullable<int> POrder_Status { get; set; }
        public Nullable<int> POrder_CreatedBy { get; set; }
        public Nullable<System.DateTime> POrder_CreatedDate { get; set; }
        public string AlertText { get; set; }
        public Nullable<decimal> MaxPerdays { get; set; }
        public Nullable<bool> OrderStockFlag { get; set; }
        public Nullable<bool> PRNFlag { get; set; }
        public Nullable<bool> SelfAdministeredFlag { get; set; }
        public Nullable<bool> TreatmentFlag { get; set; }
        public Nullable<bool> Maysubstitute { get; set; }
        public string InsulinComments { get; set; }
        public Nullable<int> RouteCode { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RequestedGiveCode { get; set; }
        public string GiveCodeText { get; set; }
        public string ProviderAdminDrugInsText { get; set; }
        public string NumberOfRefills { get; set; }
        public string NumberOfRefillsRemaining { get; set; }
        public Nullable<int> POOutBoundFileStatus { get; set; }
        public Nullable<int> POOutBoundApproval { get; set; }
        public Nullable<int> POOutBoundApprovalBy { get; set; }
        public Nullable<System.DateTime> POOutBoundApprovalOn { get; set; }
        public Nullable<int> AdministrationType { get; set; }
        public Nullable<int> NursingFreq_Id { get; set; }
        public string NurseShifts_Id { get; set; }
        public string Hour_Id { get; set; }
        public Nullable<int> TimeFormat_Id { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<int> Week_Id { get; set; }
        public Nullable<int> Month_Id { get; set; }
        public Nullable<int> OnlyOnDay { get; set; }
        public Nullable<int> ThroughDay { get; set; }
        public Nullable<int> ActiveDays { get; set; }
        public Nullable<int> HoldDays { get; set; }
        public Nullable<int> InHand { get; set; }
        public Nullable<int> Stock_Id { get; set; }
        public string Barcode { get; set; }
        public string Days { get; set; }
        public string Favourites { get; set; }
        public Nullable<int> ControlSubstanceBit { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Daw { get; set; }
        public Nullable<decimal> DispenseQty { get; set; }
        public Nullable<System.DateTime> WrittenDate { get; set; }
        public Nullable<int> DiagIndication { get; set; }
        public Nullable<int> WaitforPharmacy { get; set; }
        public Nullable<int> Hospice { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> UOM { get; set; }
        public string Sig2Quantity { get; set; }
        public Nullable<int> Sig2NursingFreq_Id { get; set; }
        public string Sig2NurseShifts_Id { get; set; }
        public string Sig2AddInsText { get; set; }
        public Nullable<int> Sig2MaxPerdays { get; set; }
        public Nullable<int> Sig2PRNFlag { get; set; }
        public string Sig3Quantity { get; set; }
        public Nullable<int> Sig3NursingFreq_Id { get; set; }
        public string Sig3NurseShifts_Id { get; set; }
        public string Sig3AddInsText { get; set; }
        public Nullable<int> Sig3MaxPerdays { get; set; }
        public Nullable<int> Sig3PRNFlag { get; set; }
        public string Sig4Quantity { get; set; }
        public Nullable<int> Sig4NursingFreq_Id { get; set; }
        public string Sig4NurseShifts_Id { get; set; }
        public string Sig4AddInsText { get; set; }
        public Nullable<int> Sig4MaxPerdays { get; set; }
        public Nullable<int> Sig4PRNFlag { get; set; }
        public string DiagIndicationText { get; set; }
        public Nullable<int> DUom { get; set; }
        public Nullable<int> Sig2DUom { get; set; }
        public Nullable<int> Sig3DUom { get; set; }
        public Nullable<int> Sig4DUom { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
