//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalAllergyInfo
    {
        public int ApprovalPAllergy_Id { get; set; }
        public Nullable<int> PAllergy_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> AllergyType_Id { get; set; }
        public Nullable<int> ClassDrugType { get; set; }
        public Nullable<int> ClassDrug_Id { get; set; }
        public string ClassDrug_Name { get; set; }
        public string NameOfCoding { get; set; }
        public string AllergySeverityCode { get; set; }
        public string AllergyReactionCode { get; set; }
        public Nullable<System.DateTime> AllergyIdentificationDate { get; set; }
        public int PAllergy_Status { get; set; }
        public Nullable<int> PAllergy_CreatedBy { get; set; }
        public System.DateTime PAllergy_CreatedDate { get; set; }
        public Nullable<int> PAOutBoundFileStatus { get; set; }
        public Nullable<int> PAOutBoundApproval { get; set; }
        public Nullable<int> PAOutBoundApprovalBy { get; set; }
        public Nullable<System.DateTime> PAOutBoundApprovalOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
