//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeDetail
    {
        public int PBarcode_Id { get; set; }
        public Nullable<int> POrder_Id { get; set; }
        public Nullable<int> Stock_Id { get; set; }
        public Nullable<int> Ekit_Id { get; set; }
        public string BarcodeDetail1 { get; set; }
        public int PBarcode_Status { get; set; }
        public Nullable<int> PBarcode_CreatedBy { get; set; }
        public System.DateTime PBarcode_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Ekit Ekit { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual CommonOrderInfo CommonOrderInfo { get; set; }
    }
}
