//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehavioralSymptomsMaster
    {
        public int BehavioralSym_ID { get; set; }
        public string BehavioralSym_Desc { get; set; }
        public int BehavioralSym_Status { get; set; }
        public Nullable<int> BehavioralSym_CreatedBy { get; set; }
        public System.DateTime BehavioralSym_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
