//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertifyDate
    {
        public int CertifyTime_ID { get; set; }
        public Nullable<System.DateTime> CertifyDate1 { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
