//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertifyOrder
    {
        public long Certify_ID { get; set; }
        public Nullable<int> CertifyTime_ID { get; set; }
        public Nullable<int> Porder_Id { get; set; }
        public Nullable<int> months { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
