//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassDrugCodingType
    {
        public int CDCodingType_Id { get; set; }
        public string CDCodingType_Name { get; set; }
        public string CDCodingType_Desc { get; set; }
        public int CDCodingType_Status { get; set; }
        public Nullable<int> CDCodingType_CreatedBy { get; set; }
        public System.DateTime CDCodingType_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
