//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColourType
    {
        public int ColourType_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> PatientType_Id { get; set; }
        public Nullable<int> ColourType_Status { get; set; }
        public Nullable<int> ColourType_CreatedBy { get; set; }
        public Nullable<System.DateTime> ColourType_CreatedOn { get; set; }
    
        public virtual PatientType PatientType { get; set; }
        public virtual User User { get; set; }
        public virtual Demographic Demographic { get; set; }
    }
}
