//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonOrderInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommonOrderInfo()
        {
            this.AddlInstructionDetails = new HashSet<AddlInstructionDetail>();
            this.AncillaryDetails = new HashSet<AncillaryDetail>();
            this.BarcodeDetails = new HashSet<BarcodeDetail>();
            this.CompoundOrders = new HashSet<CompoundOrder>();
            this.NotesInfoes = new HashSet<NotesInfo>();
            this.OutBoundFileInformations = new HashSet<OutBoundFileInformation>();
            this.QuantityDetails = new HashSet<QuantityDetail>();
            this.TreatmentDispenseInfoes = new HashSet<TreatmentDispenseInfo>();
            this.TreatmentInfoes = new HashSet<TreatmentInfo>();
            this.TreatmentRouteInfoes = new HashSet<TreatmentRouteInfo>();
            this.EncodedOrderDetails = new HashSet<EncodedOrderDetail>();
            this.DrugAdministers = new HashSet<DrugAdminister>();
        }
    
        public int POrder_Id { get; set; }
        public int Patient_Id { get; set; }
        public Nullable<int> OrderingPhysicianID { get; set; }
        public string OrderControl { get; set; }
        public string PlacerOrderNumber { get; set; }
        public string FacilityId { get; set; }
        public string PatientId { get; set; }
        public string Room { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public string PlacerGroupNumber { get; set; }
        public string OrderStatus { get; set; }
        public string ResponseFlag { get; set; }
        public string QuantityTiming { get; set; }
        public string Parent { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string EnteredBy { get; set; }
        public string EPharmacistLName { get; set; }
        public string EPharmacistFName { get; set; }
        public string VerifiedBy { get; set; }
        public string VPharmacistLName { get; set; }
        public string VPharmacistFName { get; set; }
        public Nullable<System.DateTime> VEffectivedate { get; set; }
        public string OrderingPhysicianNPI { get; set; }
        public string OPhysicianLname { get; set; }
        public string OPhysicianFname { get; set; }
        public string EntererLocation { get; set; }
        public string CallBackPhoneNumber { get; set; }
        public Nullable<System.DateTime> OrderEffectiveDate { get; set; }
        public string OrderControlCodeReason { get; set; }
        public string EnteringOrganisation { get; set; }
        public string EnteringDevice { get; set; }
        public string AltCodingSystem { get; set; }
        public string AdvBeneficiaryNoticeCode { get; set; }
        public string OrderingFacilityName { get; set; }
        public string OrderingFacilityAddress1 { get; set; }
        public string OrderingFacilityAddress2 { get; set; }
        public string OrderingFacilityCity { get; set; }
        public string OrderingFacilityState { get; set; }
        public string OrderingFacilityZip { get; set; }
        public string OrderingFacilityPhone { get; set; }
        public string OrderingPhysicianAddress1 { get; set; }
        public string OrderingPhysicianAddress2 { get; set; }
        public string OrderingPhysicianCity { get; set; }
        public string OrderingPhysicianState { get; set; }
        public string OrderingProviderZip { get; set; }
        public string OrderStatusModifier { get; set; }
        public string AdvBeneficiaryNoticeOverrideReason { get; set; }
        public Nullable<System.DateTime> ExpectedAvailabilityDate { get; set; }
        public string ConfidentialityCode { get; set; }
        public string OrderType { get; set; }
        public string EntererAuthorizationMode { get; set; }
        public int POrder_Status { get; set; }
        public Nullable<int> POrder_CreatedBy { get; set; }
        public System.DateTime POrder_CreatedDate { get; set; }
        public Nullable<int> POOutBoundFileStatus { get; set; }
        public Nullable<int> POOutBoundApproval { get; set; }
        public Nullable<int> POOutBoundApprovalBy { get; set; }
        public Nullable<System.DateTime> POOutBoundApprovalOn { get; set; }
        public Nullable<bool> OrderStockFlag { get; set; }
        public string DrFirstPrescriptionId { get; set; }
        public Nullable<int> File_Id { get; set; }
        public Nullable<int> OldPatient_Id { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Daw { get; set; }
        public Nullable<decimal> DispenseQty { get; set; }
        public Nullable<System.DateTime> WrittenDate { get; set; }
        public Nullable<int> DiagIndication { get; set; }
        public Nullable<int> WaitforPharmacy { get; set; }
        public Nullable<int> Hospice { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> UOM { get; set; }
        public string DiagIndicationText { get; set; }
        public string PharmacyName { get; set; }
        public Nullable<decimal> DaysSupply { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddlInstructionDetail> AddlInstructionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AncillaryDetail> AncillaryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarcodeDetail> BarcodeDetails { get; set; }
        public virtual Demographic Demographic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompoundOrder> CompoundOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesInfo> NotesInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutBoundFileInformation> OutBoundFileInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuantityDetail> QuantityDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentDispenseInfo> TreatmentDispenseInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentInfo> TreatmentInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentRouteInfo> TreatmentRouteInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncodedOrderDetail> EncodedOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugAdminister> DrugAdministers { get; set; }
    }
}
