//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyHlCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyHlCategory()
        {
            this.CompanyHLEvents = new HashSet<CompanyHLEvent>();
        }
    
        public int CompanyHlCategory_Id { get; set; }
        public Nullable<int> CompanyConfig_Id { get; set; }
        public Nullable<int> FteCategory_Id { get; set; }
    
        public virtual CompanyConfig CompanyConfig { get; set; }
        public virtual FTECategory FTECategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyHLEvent> CompanyHLEvents { get; set; }
    }
}
