//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyBedConfigs = new HashSet<CompanyBedConfig>();
            this.CompanyConfigs = new HashSet<CompanyConfig>();
            this.DrFirstFileDatas = new HashSet<DrFirstFileData>();
            this.Facilities = new HashSet<Facility>();
            this.FileAckInformations = new HashSet<FileAckInformation>();
            this.FileInformations = new HashSet<FileInformation>();
            this.HLSevenCompanyConfigs = new HashSet<HLSevenCompanyConfig>();
            this.OutBoundFileInformations = new HashSet<OutBoundFileInformation>();
            this.PatientTypes = new HashSet<PatientType>();
            this.HLSevenOutboundDisplayCompanyConfigs = new HashSet<HLSevenOutboundDisplayCompanyConfig>();
        }
    
        public int Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Addr1 { get; set; }
        public string Company_Addr2 { get; set; }
        public string Company_Zip { get; set; }
        public string Company_City { get; set; }
        public string Company_State { get; set; }
        public Nullable<int> Company_CountryId { get; set; }
        public string Company_Phone { get; set; }
        public string Company_Fax { get; set; }
        public string Company_Email { get; set; }
        public string Com_ContactPerson { get; set; }
        public string Com_ContactPhone { get; set; }
        public string Company_EIN { get; set; }
        public byte[] Company_Logo { get; set; }
        public string Company_UniqueId { get; set; }
        public Nullable<int> ApprovalFlag { get; set; }
        public Nullable<int> Fingersdesc_Id { get; set; }
        public Nullable<int> TimeFormat { get; set; }
        public int Company_Status { get; set; }
        public Nullable<int> Company_CreatedBy { get; set; }
        public System.DateTime Company_CreatedDate { get; set; }
        public byte[] Company_FooterLogo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBedConfig> CompanyBedConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyConfig> CompanyConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrFirstFileData> DrFirstFileDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facility> Facilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileAckInformation> FileAckInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileInformation> FileInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenCompanyConfig> HLSevenCompanyConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutBoundFileInformation> OutBoundFileInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientType> PatientTypes { get; set; }
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenOutboundDisplayCompanyConfig> HLSevenOutboundDisplayCompanyConfigs { get; set; }
    }
}
