//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBedConfig
    {
        public int BedConfig_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public Nullable<int> Floor_Id { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
        public Nullable<int> Wing_Id { get; set; }
        public Nullable<int> Room_Id { get; set; }
        public Nullable<int> Bed_Id { get; set; }
        public int BedConfig_Status { get; set; }
        public Nullable<int> BedConfig_CreatedBy { get; set; }
        public System.DateTime BedConfig_CreatedDate { get; set; }
    
        public virtual Bed Bed { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
        public virtual Wing Wing { get; set; }
        public virtual Company Company { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
