//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyHLEvent
    {
        public int CompanyHLEvent_Id { get; set; }
        public Nullable<int> CompanyHlCategory_Id { get; set; }
        public Nullable<int> EventCat_Id { get; set; }
    
        public virtual CompanyHlCategory CompanyHlCategory { get; set; }
        public virtual EventCategory EventCategory { get; set; }
    }
}
