//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyConfig()
        {
            this.CompanyHlCategories = new HashSet<CompanyHlCategory>();
        }
    
        public int CompanyConfig_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> ApprovalFlag { get; set; }
        public Nullable<int> Fingersdesc_Id { get; set; }
        public Nullable<int> TimeFormat { get; set; }
        public Nullable<int> Hl7Configured { get; set; }
        public Nullable<int> HLDirectionalWay_Id { get; set; }
        public Nullable<int> CompanyConfig_Status { get; set; }
        public Nullable<int> CompanyConfig_CreatedBy { get; set; }
        public Nullable<System.DateTime> CompanyConfig_CreatedOn { get; set; }
        public Nullable<int> StockReport_Id { get; set; }
        public Nullable<int> DrFirstRequired { get; set; }
        public Nullable<int> Physician_Id { get; set; }
    
        public virtual Fingersdesc Fingersdesc { get; set; }
        public virtual HLDirectionalWay HLDirectionalWay { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyHlCategory> CompanyHlCategories { get; set; }
        public virtual StockReport StockReport { get; set; }
        public virtual Company Company { get; set; }
        public virtual PhysicianDetail PhysicianDetail { get; set; }
    }
}
