//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlSubstanceCount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlSubstanceCount()
        {
            this.ControlSubstanceTrans = new HashSet<ControlSubstanceTran>();
        }
    
        public int ControlSubstance_Id { get; set; }
        public Nullable<int> Porder_Id { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> CertifiedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> CertifiedDate { get; set; }
        public int ControlSubstance_Status { get; set; }
        public System.DateTime ControlSubstance_CreatedDate { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
        public string InitialQuantity { get; set; }
        public Nullable<int> ConsolidateFlag { get; set; }
        public Nullable<int> PQuantity_Id { get; set; }
        public Nullable<int> CheckInFlag { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSubstanceTran> ControlSubstanceTrans { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
