//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlSubstanceTran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlSubstanceTran()
        {
            this.ControlSubstanceReasons = new HashSet<ControlSubstanceReason>();
        }
    
        public int TransCS_Id { get; set; }
        public Nullable<int> ControlSubstance_Id { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> CertifiedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> CertifiedDate { get; set; }
        public int TransCS_Status { get; set; }
        public System.DateTime TransCS_CreatedDate { get; set; }
        public Nullable<int> ConsolidateFlag { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ControlSubstanceCount ControlSubstanceCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSubstanceReason> ControlSubstanceReasons { get; set; }
    }
}
