//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultScreen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefaultScreen()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int DefaultScreen_Id { get; set; }
        public Nullable<int> Screen_Id { get; set; }
        public Nullable<int> DefaultScreen_Status { get; set; }
        public Nullable<int> DefaultScreen_CreatedBy { get; set; }
        public Nullable<System.DateTime> DefaultScreen_CreatedOn { get; set; }
    
        public virtual Screen Screen { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
