//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocAdministerTran
    {
        public long DATrans_Id { get; set; }
        public Nullable<long> DrugAdminister_Id { get; set; }
        public Nullable<int> Dacd_Id { get; set; }
        public Nullable<int> ManualDocumentedBy { get; set; }
        public Nullable<System.DateTime> ManualDocumentedDate { get; set; }
        public Nullable<int> AdminsterBy { get; set; }
        public Nullable<System.DateTime> AdminsterOn { get; set; }
        public string Reason { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual DrugAdminister DrugAdminister { get; set; }
    }
}
