//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocFolder
    {
        public int FolderID { get; set; }
        public string FolderName { get; set; }
        public Nullable<int> FolderParentID { get; set; }
        public int Folder_Status { get; set; }
        public Nullable<int> Folder_CreatedBy { get; set; }
        public System.DateTime Folder_CreatedDate { get; set; }
        public string FolderLocation { get; set; }
    
        public virtual User User { get; set; }
    }
}
