//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrFirstXMLTran
    {
        public int DrFirstXMLTrans_Id { get; set; }
        public string RcopiaID { get; set; }
        public string CreatedDate { get; set; }
        public string CompletedDate { get; set; }
        public string SignedDate { get; set; }
        public string StopDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedDate { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string IntendedUse { get; set; }
        public string Deleted { get; set; }
        public string Voided { get; set; }
        public string Denied { get; set; }
        public string ExternalID { get; set; }
        public string NeedsReview { get; set; }
        public string PatientID { get; set; }
        public string PatientExternalID { get; set; }
        public string RcopiaPracticeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ProviderID { get; set; }
        public string Username { get; set; }
        public string ProviderExternalID { get; set; }
        public string ProviderNPI { get; set; }
        public string ProviderFirstName { get; set; }
        public string ProviderLastName { get; set; }
        public string ProviderDEA { get; set; }
        public string PreparerID { get; set; }
        public string PreparerName { get; set; }
        public string PreparerExternalID { get; set; }
        public string PreparerFirstName { get; set; }
        public string PreparerLastName { get; set; }
        public string PharmacyID { get; set; }
        public string PharmacyMasterID { get; set; }
        public string PharmacyDeleted { get; set; }
        public string NCPDPID { get; set; }
        public string PharmacyName { get; set; }
        public string PharmacyAddress1 { get; set; }
        public string PharmacyAddress2 { get; set; }
        public string PharmacyCity { get; set; }
        public string PharmacyState { get; set; }
        public string PharmacyZip { get; set; }
        public string PharmacyPhone { get; set; }
        public string PharmacyFax { get; set; }
        public string PharmacyIs24Hour { get; set; }
        public string PharmacyLevel3 { get; set; }
        public string PharmacyElectronic { get; set; }
        public string PharmacyMailOrder { get; set; }
        public string PharmacyRequiresEligibility { get; set; }
        public string PharmacyRetail { get; set; }
        public string PharmacyLongTermCare { get; set; }
        public string PharmacySpecialty { get; set; }
        public string PharmacyCanReceiveControlledSubstance { get; set; }
        public string PharmacyInHouseDispensing { get; set; }
        public string PharmacyCompounding { get; set; }
        public string PharmacyDurableMedicalEquipment { get; set; }
        public string PharmacyKiosk { get; set; }
        public string NDCID { get; set; }
        public string FirstDataBankMedID { get; set; }
        public string DrugId { get; set; }
        public string PrescriptionID { get; set; }
        public string DrugDescription { get; set; }
        public string BrandName { get; set; }
        public string GenericName { get; set; }
        public string Schedule { get; set; }
        public string BrandType { get; set; }
        public string LegendStatus { get; set; }
        public string RouteInfo { get; set; }
        public string Form { get; set; }
        public string Strength { get; set; }
        public string DoAction { get; set; }
        public string Dose { get; set; }
        public string DoseUnit { get; set; }
        public string TakeBy { get; set; }
        public string DoseTiming { get; set; }
        public string DoseOther { get; set; }
        public string Duration { get; set; }
        public string Quantity { get; set; }
        public string QuantityUnit { get; set; }
        public string Refills { get; set; }
        public string SubstitutionPermitted { get; set; }
        public string OtherNotes { get; set; }
        public string PatientNotes { get; set; }
        public string MaximumDailyDose { get; set; }
        public string MaximumDailyDoseUnit { get; set; }
        public string Comments { get; set; }
        public string FormularyAction { get; set; }
        public Nullable<int> DrFirstXMLTrans_Approval { get; set; }
        public Nullable<int> DrFirstXMLTrans_ApprovalBy { get; set; }
        public Nullable<System.DateTime> DrFirstXMLTrans_ApprovalOn { get; set; }
    }
}
