//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrFirstOrderXMLTran
    {
        public int DrFirstOrder_Id { get; set; }
        public string RcopiaID { get; set; }
        public string PatientExternalID { get; set; }
        public string NDCID { get; set; }
        public string FirstDataBankMedID { get; set; }
        public string DrugId { get; set; }
        public string PrescriptionID { get; set; }
        public string DrugDescription { get; set; }
        public string BrandName { get; set; }
        public string GenericName { get; set; }
        public string Schedule { get; set; }
        public string BrandType { get; set; }
        public string LegendStatus { get; set; }
        public string RouteInfo { get; set; }
        public string Form { get; set; }
        public string Strength { get; set; }
        public string DoAction { get; set; }
        public string Dose { get; set; }
        public string DoseUnit { get; set; }
        public string TakeBy { get; set; }
        public string DoseTiming { get; set; }
        public string DoseOther { get; set; }
        public string Duration { get; set; }
        public string Quantity { get; set; }
        public string QuantityUnit { get; set; }
        public string Refills { get; set; }
        public string SubstitutionPermitted { get; set; }
        public string OtherNotes { get; set; }
        public string PatientNotes { get; set; }
        public string MaximumDailyDose { get; set; }
        public string MaximumDailyDoseUnit { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DrFirstOrder_CreatedDate { get; set; }
        public Nullable<int> DrFirstOrderXMLTrans_Approval { get; set; }
        public Nullable<int> DrFirstOrderXMLTrans_ApprovalBy { get; set; }
        public Nullable<System.DateTime> DrFirstOrderXMLTrans_ApprovalOn { get; set; }
    }
}
