//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrFirstFileData
    {
        public long DrFirstFile_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string PatientMRNumber { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
