//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugActiveday
    {
        public long Activeday_Id { get; set; }
        public Nullable<int> DAdmin_Id { get; set; }
        public Nullable<int> ActiveDay { get; set; }
        public Nullable<System.DateTime> Activeday_CreatedDate { get; set; }
    
        public virtual DrugAdministrationTime DrugAdministrationTime { get; set; }
    }
}
