//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public int Drug_Id { get; set; }
        public string TradeName { get; set; }
        public string GenericName { get; set; }
        public string Form { get; set; }
        public string Route { get; set; }
        public string Dosage { get; set; }
        public string Indication { get; set; }
        public Nullable<int> PsychiatricIndication { get; set; }
        public Nullable<int> Drug_Status { get; set; }
        public Nullable<int> Drug_CreatedBy { get; set; }
        public Nullable<System.DateTime> Drug_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
