//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugAdminister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrugAdminister()
        {
            this.DocAdministerTrans = new HashSet<DocAdministerTran>();
            this.EkitAdministers = new HashSet<EkitAdminister>();
            this.NurseComments = new HashSet<NurseComment>();
        }
    
        public long DrugAdminister_Id { get; set; }
        public Nullable<int> DAdmin_Id { get; set; }
        public Nullable<int> Porder_Id { get; set; }
        public Nullable<int> PQuantity_Id { get; set; }
        public Nullable<System.DateTime> AdminsterSchedule { get; set; }
        public Nullable<int> NurseShifts_Id { get; set; }
        public string AdministerComment { get; set; }
        public string PRNComment { get; set; }
        public string SeventyTwoComment { get; set; }
        public Nullable<int> MedicationReason_ID { get; set; }
        public Nullable<int> AdminsterStatus { get; set; }
        public Nullable<int> AdminsterBy { get; set; }
        public Nullable<System.DateTime> AdminsterOn { get; set; }
        public Nullable<int> PRNCommentBy { get; set; }
        public Nullable<System.DateTime> PRNCommentOn { get; set; }
        public Nullable<int> SeventyTwoCommentBy { get; set; }
        public Nullable<System.DateTime> SeventyTwoCommentOn { get; set; }
        public Nullable<int> BiometricBypass { get; set; }
        public string BiometricBypassReason { get; set; }
        public Nullable<int> BCScanner { get; set; }
        public Nullable<decimal> DrugQuantity { get; set; }
        public Nullable<int> ManualDocumentedBy { get; set; }
        public Nullable<System.DateTime> ManualDocumentedDate { get; set; }
        public Nullable<int> NotificationStat { get; set; }
        public Nullable<int> EkitAdminister { get; set; }
        public string additionalcomments { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Ekit_Id { get; set; }
        public Nullable<int> is_deleted { get; set; }
    
        public virtual MedicationReason MedicationReason { get; set; }
        public virtual NurseShift NurseShift { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual CommonOrderInfo CommonOrderInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocAdministerTran> DocAdministerTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EkitAdminister> EkitAdministers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseComment> NurseComments { get; set; }
    }
}
