//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugAdministrationTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrugAdministrationTime()
        {
            this.DrugActivedays = new HashSet<DrugActiveday>();
        }
    
        public int DAdmin_Id { get; set; }
        public int POrder_Id { get; set; }
        public Nullable<int> PQuantity_Id { get; set; }
        public Nullable<int> AdministrationType { get; set; }
        public Nullable<int> NursingFreq_Id { get; set; }
        public string NurseShifts_Id { get; set; }
        public Nullable<int> Hour_Id { get; set; }
        public Nullable<int> TimeFormat_Id { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<int> Week_Id { get; set; }
        public Nullable<int> Month_Id { get; set; }
        public Nullable<int> OnlyOnDay { get; set; }
        public Nullable<int> ThroughDay { get; set; }
        public Nullable<int> ActiveDays { get; set; }
        public Nullable<int> HoldDays { get; set; }
        public int DAdmin_Status { get; set; }
        public Nullable<int> DAdmin_CreatedBy { get; set; }
        public Nullable<System.DateTime> DAdmin_CreatedDate { get; set; }
        public Nullable<int> DUom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugActiveday> DrugActivedays { get; set; }
    }
}
