//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugOrderMaster
    {
        public int DrugOrderMaster_Id { get; set; }
        public string NDC { get; set; }
        public string GPI { get; set; }
        public string DrugName { get; set; }
        public string Strength { get; set; }
        public string DosageForm { get; set; }
        public string ControlledSubstanceSchedule { get; set; }
        public Nullable<int> DrugOrderMaster_Status { get; set; }
        public Nullable<int> DrugOrderMaster_CreatedBy { get; set; }
        public Nullable<System.DateTime> DrugOrderMaster_CreatedDate { get; set; }
        public string Route { get; set; }
        public string RouteDescription { get; set; }
    }
}
