//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ekit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ekit()
        {
            this.BarcodeDetails = new HashSet<BarcodeDetail>();
            this.EkitAdministers = new HashSet<EkitAdminister>();
            this.EKitControlSubstanceTrans = new HashSet<EKitControlSubstanceTran>();
        }
    
        public int Ekit_Id { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
        public string DrugName { get; set; }
        public string InHand { get; set; }
        public string NDC { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> Ekit_Status { get; set; }
        public Nullable<int> Ekit_CreatedBy { get; set; }
        public Nullable<System.DateTime> Ekit_CreatedOn { get; set; }
        public string GPICode { get; set; }
        public Nullable<int> TrackableBit { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public Nullable<int> Sharedekitbit { get; set; }
        public string InitialQuantity { get; set; }
        public Nullable<int> CertifiedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> CertifiedDate { get; set; }
        public Nullable<int> CheckInFlag { get; set; }
        public Nullable<int> ControlSubstance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarcodeDetail> BarcodeDetails { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EkitAdminister> EkitAdministers { get; set; }
        public virtual Facility Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EKitControlSubstanceTran> EKitControlSubstanceTrans { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
