//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkitControlSubstanceReason
    {
        public long EkCSReason_Id { get; set; }
        public Nullable<int> Ekit_Id { get; set; }
        public string Reason { get; set; }
        public Nullable<int> EkCSReason_CreatedBy { get; set; }
        public Nullable<System.DateTime> EkCSReason_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
