//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkitAdminister
    {
        public int EkitAdminister_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<long> DrugAdminister_Id { get; set; }
        public Nullable<int> Ekit_Id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<int> EkitAdministerBy { get; set; }
        public Nullable<System.DateTime> EkitAdministerOn { get; set; }
    
        public virtual Ekit Ekit { get; set; }
        public virtual User User { get; set; }
        public virtual Demographic Demographic { get; set; }
        public virtual DrugAdminister DrugAdminister { get; set; }
    }
}
