//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKitControlSubstanceTran
    {
        public int EkTransCS_Id { get; set; }
        public Nullable<int> Ekit_Id { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> CertifiedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> CertifiedDate { get; set; }
        public int EkTransCS_Status { get; set; }
        public System.DateTime EkTransCS_CreatedDate { get; set; }
    
        public virtual Ekit Ekit { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
