//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventCategory()
        {
            this.CompanyHLEvents = new HashSet<CompanyHLEvent>();
        }
    
        public int EventCat_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string EventCat_Code { get; set; }
        public string EventCat_Desc { get; set; }
        public string EventCat_ShortCode { get; set; }
        public Nullable<int> EventCat_Type { get; set; }
        public int EventCat_Status { get; set; }
        public Nullable<int> EventCat_CreatedBy { get; set; }
        public System.DateTime EventCat_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyHLEvent> CompanyHLEvents { get; set; }
    }
}
