//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facility()
        {
            this.CompanyBedConfigs = new HashSet<CompanyBedConfig>();
            this.NursingFrequencyConfigs = new HashSet<NursingFrequencyConfig>();
            this.RecentFacs = new HashSet<RecentFac>();
            this.Ekits = new HashSet<Ekit>();
            this.Stocks = new HashSet<Stock>();
            this.tblRDCMailConfigs = new HashSet<tblRDCMailConfig>();
            this.NursingStations = new HashSet<NursingStation>();
            this.PhysicianDetails = new HashSet<PhysicianDetail>();
        }
    
        public int Facility_Id { get; set; }
        public int Company_Id { get; set; }
        public string Facility_Name { get; set; }
        public string Facility_Addr1 { get; set; }
        public string Facility_Addr2 { get; set; }
        public string Facility_Zip { get; set; }
        public string Facility_City { get; set; }
        public string Facility_State { get; set; }
        public Nullable<int> Facility_CountryId { get; set; }
        public string Facility_Phone { get; set; }
        public string Facility_Fax { get; set; }
        public string Facility_ContactName { get; set; }
        public string Facility_ContactPhone { get; set; }
        public string Facility_ShortName { get; set; }
        public byte[] Facility_Logo { get; set; }
        public int Facility_Status { get; set; }
        public Nullable<int> Facility_CreatedBy { get; set; }
        public System.DateTime Facility_CreatedDate { get; set; }
        public Nullable<int> TZ_Id { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBedConfig> CompanyBedConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingFrequencyConfig> NursingFrequencyConfigs { get; set; }
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecentFac> RecentFacs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ekit> Ekits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRDCMailConfig> tblRDCMailConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingStation> NursingStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianDetail> PhysicianDetails { get; set; }
    }
}
