//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileInformation()
        {
            this.FileInfoErrors = new HashSet<FileInfoError>();
        }
    
        public int File_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public int File_Category { get; set; }
        public string File_Name { get; set; }
        public string File_Data { get; set; }
        public string Event { get; set; }
        public int File_Status { get; set; }
        public string File_Error { get; set; }
        public System.DateTime File_CreatedDate { get; set; }
        public Nullable<int> File_CreatedBy { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileInfoError> FileInfoErrors { get; set; }
        public virtual Company Company { get; set; }
    }
}
