//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAckInformation
    {
        public int FileAckInformation_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string File_Name { get; set; }
        public string FileAck_Data { get; set; }
        public Nullable<int> File_Id { get; set; }
        public int FileAck_Status { get; set; }
        public Nullable<int> FileAck_CreatedBy { get; set; }
        public System.DateTime File_CreatedDate { get; set; }
        public Nullable<int> File_Status { get; set; }
        public Nullable<int> File_StatusSent { get; set; }
        public string PatientMrNumber { get; set; }
    
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
    }
}
