//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fingersdesc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fingersdesc()
        {
            this.CompanyConfigs = new HashSet<CompanyConfig>();
        }
    
        public int Fingersdesc_Id { get; set; }
        public string FingersDesc1 { get; set; }
        public Nullable<int> Fingersdesc_Status { get; set; }
        public Nullable<int> Fingersdesc_CreatedBy { get; set; }
        public System.DateTime Fingersdesc_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyConfig> CompanyConfigs { get; set; }
    }
}
