//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FooterLogo
    {
        public int Footer_Id { get; set; }
        public byte[] Footer_Image { get; set; }
        public int Footer_Status { get; set; }
        public Nullable<System.DateTime> Footer_CreatedOn { get; set; }
        public Nullable<int> Footer_CreatedBy { get; set; }
    }
}
