//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrequencyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FrequencyMaster()
        {
            this.NursingFrequencyConfigs = new HashSet<NursingFrequencyConfig>();
        }
    
        public int Frequency_Id { get; set; }
        public string Frequency_Code { get; set; }
        public string Frequency_Shortname { get; set; }
        public string Frequency_Description { get; set; }
        public int Frequency_Status { get; set; }
        public Nullable<int> Frequency_CreatedBy { get; set; }
        public System.DateTime Frequency_CreatedDate { get; set; }
        public Nullable<int> Frequency_PRN { get; set; }
        public string Freq_Group { get; set; }
        public Nullable<int> Freq_Times { get; set; }
        public string Freq_Descalert { get; set; }
        public string Freq_Descalert1 { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingFrequencyConfig> NursingFrequencyConfigs { get; set; }
    }
}
