//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTEConfiguration
    {
        public int FteConfig_Id { get; set; }
        public string ServerIp { get; set; }
        public int Category { get; set; }
        public Nullable<int> ConnectionType { get; set; }
        public string Port { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int FteConfig_Status { get; set; }
        public Nullable<int> FteConfig_CreatedBy { get; set; }
        public System.DateTime FteConfig_CreatedDate { get; set; }
        public string FteConnectionStatus { get; set; }
    
        public virtual FTECategory FTECategory { get; set; }
        public virtual FteConnection FteConnection { get; set; }
        public virtual User User { get; set; }
    }
}
