//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTECategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FTECategory()
        {
            this.CompanyHlCategories = new HashSet<CompanyHlCategory>();
            this.FTEConfigurations = new HashSet<FTEConfiguration>();
        }
    
        public int FteCategory_Id { get; set; }
        public string FteCategory_Desc { get; set; }
        public int FteCategory_Status { get; set; }
        public Nullable<int> FteCategory_CreatedBy { get; set; }
        public System.DateTime FteCategory_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyHlCategory> CompanyHlCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FTEConfiguration> FTEConfigurations { get; set; }
    }
}
