//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HLSevenSegmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HLSevenSegmentDetail()
        {
            this.HLSevenCompanyConfigs = new HashSet<HLSevenCompanyConfig>();
        }
    
        public int SegDetail_Id { get; set; }
        public int Segment_Id { get; set; }
        public string SegDetail_Desc { get; set; }
        public Nullable<int> SegDetail_Length { get; set; }
        public Nullable<int> SegDetail_Sequence { get; set; }
        public Nullable<int> SegDetail_SubSequence { get; set; }
        public int SegDetail_Status { get; set; }
        public Nullable<int> SegDetail_CreatedBy { get; set; }
        public System.DateTime SegDetail_CreatedDate { get; set; }
        public string SegDetail_ColumnID { get; set; }
        public string File_Values { get; set; }
        public Nullable<int> HlSequence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenCompanyConfig> HLSevenCompanyConfigs { get; set; }
        public virtual HLSevenSegment HLSevenSegment { get; set; }
        public virtual User User { get; set; }
    }
}
