//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HLSevenCompanyConfig
    {
        public int HLConfig_Id { get; set; }
        public int Company_Id { get; set; }
        public int SegDetail_Id { get; set; }
        public int SegDetailConfig_Id { get; set; }
        public Nullable<int> SegDisplay_Id { get; set; }
        public int HLConfig_Status { get; set; }
        public Nullable<int> HLConfig_CreatedBy { get; set; }
        public System.DateTime HLConfig_CreatedDate { get; set; }
    
        public virtual HLSevenSegmentDetail HLSevenSegmentDetail { get; set; }
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
    }
}
