//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HLSevenOutboundDisplayCompanyConfig
    {
        public int OHLConfig_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public int OSegDetail_Id { get; set; }
        public Nullable<int> DisplayConfigId { get; set; }
        public Nullable<int> OHLConfig_Status { get; set; }
        public Nullable<int> OHLConfig_CreatedBy { get; set; }
        public Nullable<System.DateTime> OHLConfig_CreatedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual HLSevenOutboundDisplaySegmentDetail HLSevenOutboundDisplaySegmentDetail { get; set; }
        public virtual User User { get; set; }
    }
}
