//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HLSevenOutboundDisplaySegmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HLSevenOutboundDisplaySegmentDetail()
        {
            this.HLSevenOutboundDisplayCompanyConfigs = new HashSet<HLSevenOutboundDisplayCompanyConfig>();
        }
    
        public int OSegDetail_Id { get; set; }
        public int OSegment_Id { get; set; }
        public string OSegDetail_Desc { get; set; }
        public Nullable<int> HlSequence { get; set; }
        public Nullable<int> OSegDetail_Status { get; set; }
        public Nullable<int> OSegDetail_CreatedBy { get; set; }
        public Nullable<System.DateTime> OSegDetail_CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenOutboundDisplayCompanyConfig> HLSevenOutboundDisplayCompanyConfigs { get; set; }
        public virtual HLSevenOutboundDisplaySegment HLSevenOutboundDisplaySegment { get; set; }
        public virtual User User { get; set; }
    }
}
