//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HLSevenSegment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HLSevenSegment()
        {
            this.HLSevenSegmentDetails = new HashSet<HLSevenSegmentDetail>();
        }
    
        public int Segment_Id { get; set; }
        public string Segment_Desc { get; set; }
        public string Segment_Code { get; set; }
        public string Segment_Table { get; set; }
        public int Segment_Status { get; set; }
        public Nullable<int> Segment_CreatedBy { get; set; }
        public System.DateTime Segment_CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenSegmentDetail> HLSevenSegmentDetails { get; set; }
        public virtual User User { get; set; }
    }
}
