//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hour()
        {
            this.NurseShifts = new HashSet<NurseShift>();
            this.NurseShifts1 = new HashSet<NurseShift>();
            this.NursingFrequencyConfigs = new HashSet<NursingFrequencyConfig>();
            this.NursingFCTimes = new HashSet<NursingFCTime>();
        }
    
        public int Hour_Id { get; set; }
        public string Hour_Desc { get; set; }
        public int Hour_Status { get; set; }
        public Nullable<int> Hour_CreatedBy { get; set; }
        public System.DateTime Hour_Createddate { get; set; }
        public string RegularTime { get; set; }
        public string RegularTimeFormat { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseShift> NurseShifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseShift> NurseShifts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingFrequencyConfig> NursingFrequencyConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingFCTime> NursingFCTimes { get; set; }
    }
}
