//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICD10
    {
        public int ICD10_Id { get; set; }
        public string ICD10_RawFormat { get; set; }
        public string ICD10_Formatted { get; set; }
        public string ICD10_Description { get; set; }
        public int ICD10_Status { get; set; }
        public Nullable<int> ICD10_CreatedBy { get; set; }
        public System.DateTime ICD10_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
