//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportFile
    {
        public long ImportFile_Id { get; set; }
        public string ImportFile_Name { get; set; }
        public Nullable<System.DateTime> EncryptedDate { get; set; }
        public Nullable<System.DateTime> DecryptedDate { get; set; }
        public Nullable<int> ImportFile_Status { get; set; }
        public Nullable<int> ImportFile_CreatedBy { get; set; }
        public Nullable<System.DateTime> ImportFile_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
