//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationType
    {
        public int Integration_TypeId { get; set; }
        public string IntegrationType_Desc { get; set; }
        public int IntegrationType_Status { get; set; }
        public Nullable<int> IntegrationType_CreatedBy { get; set; }
        public System.DateTime IntegrationType_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
