//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailBox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MailBox()
        {
            this.MailFavourites = new HashSet<MailFavourite>();
            this.MailReads = new HashSet<MailRead>();
        }
    
        public int MailBox_Id { get; set; }
        public Nullable<int> Fromuser_Id { get; set; }
        public string Touser_Id { get; set; }
        public string ToMalId { get; set; }
        public string CcUser_Id { get; set; }
        public string Subject { get; set; }
        public string MailBody { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<int> MailBox_Status { get; set; }
        public Nullable<System.DateTime> MailBox_Date { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailFavourite> MailFavourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailRead> MailReads { get; set; }
    }
}
