//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailFavourite
    {
        public int MailFavourite_Id { get; set; }
        public Nullable<int> MailBox_Id { get; set; }
        public Nullable<int> user_Id { get; set; }
        public Nullable<int> MailFavourite_Status { get; set; }
        public Nullable<System.DateTime> MailFavourite_date { get; set; }
    
        public virtual User User { get; set; }
        public virtual MailBox MailBox { get; set; }
    }
}
