//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailConfig
    {
        public int ID { get; set; }
        public Nullable<int> Port { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public string Host { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime Createddate { get; set; }
    
        public virtual User User { get; set; }
    }
}
