//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicationReason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicationReason()
        {
            this.DrugAdministers = new HashSet<DrugAdminister>();
        }
    
        public int MedicationReason_ID { get; set; }
        public string MedicationReason_Desc { get; set; }
        public int MedicationReason_Status { get; set; }
        public Nullable<int> MedicationReason_CreatedBy { get; set; }
        public System.DateTime MedicationReason_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugAdminister> DrugAdministers { get; set; }
    }
}
