//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Messages_Id { get; set; }
        public Nullable<int> Conversation_Id { get; set; }
        public Nullable<int> Sender_Id { get; set; }
        public string Message_Type { get; set; }
        public string Message1 { get; set; }
        public string Attachment_Thumb_Url { get; set; }
        public string Attachment_Url { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Guid { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual User2 User { get; set; }
    }
}
