//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesInfo
    {
        public int PNote_id { get; set; }
        public int POrder_Id { get; set; }
        public string SourceOfComment { get; set; }
        public string Comment { get; set; }
        public string CommentType { get; set; }
        public int PNote_Status { get; set; }
        public Nullable<int> PNote_CreatedBy { get; set; }
        public System.DateTime PNote_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual CommonOrderInfo CommonOrderInfo { get; set; }
    }
}
