//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NursingFrequencyConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NursingFrequencyConfig()
        {
            this.NursingFCTimes = new HashSet<NursingFCTime>();
        }
    
        public int NursingFreq_Id { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public Nullable<int> NursingStation_Id { get; set; }
        public Nullable<int> Floor_Id { get; set; }
        public Nullable<int> Wing_Id { get; set; }
        public Nullable<int> Frequency_Id { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> TimeFormat_ID { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<int> Week_Id { get; set; }
        public Nullable<int> Month_Id { get; set; }
        public Nullable<int> OnlyOnDay { get; set; }
        public Nullable<int> ThroughDay { get; set; }
        public Nullable<int> ActiveDays { get; set; }
        public Nullable<int> HoldDays { get; set; }
        public int NursingFreq_Status { get; set; }
        public Nullable<int> NursingFreq_CreatedBy { get; set; }
        public System.DateTime NursingFreq_CreatedDate { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual FrequencyMaster FrequencyMaster { get; set; }
        public virtual Hour Hour { get; set; }
        public virtual Month Month { get; set; }
        public virtual NursingFrequencyConfig NursingFrequencyConfig1 { get; set; }
        public virtual NursingFrequencyConfig NursingFrequencyConfig2 { get; set; }
        public virtual User User { get; set; }
        public virtual Week Week { get; set; }
        public virtual Wing Wing { get; set; }
        public virtual Facility Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingFCTime> NursingFCTimes { get; set; }
        public virtual TimeFormat TimeFormat { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
