//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NursingStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NursingStation()
        {
            this.AlertTexts = new HashSet<AlertText>();
            this.CompanyBedConfigs = new HashSet<CompanyBedConfig>();
            this.Ekits = new HashSet<Ekit>();
            this.NurseShifts = new HashSet<NurseShift>();
            this.NurseStationHierarchies = new HashSet<NurseStationHierarchy>();
            this.NursingFrequencyConfigs = new HashSet<NursingFrequencyConfig>();
            this.NursingSchedules = new HashSet<NursingSchedule>();
            this.ControlSubstanceCounts = new HashSet<ControlSubstanceCount>();
            this.Stocks = new HashSet<Stock>();
            this.tblRDCMailConfigs = new HashSet<tblRDCMailConfig>();
            this.UserRoleFacilityConfigs = new HashSet<UserRoleFacilityConfig>();
            this.PhysicianDetails = new HashSet<PhysicianDetail>();
        }
    
        public int NurseStation_Id { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public string NurseStation_Code { get; set; }
        public string NurseStation_Name { get; set; }
        public Nullable<int> DefaultPhysician_Id { get; set; }
        public int NurseStation_Status { get; set; }
        public Nullable<int> NurseStation_CreatedBy { get; set; }
        public System.DateTime NurseStation_CreatedDate { get; set; }
        public Nullable<int> Default_Pharmacy { get; set; }
        public string Backup_Pharmacy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertText> AlertTexts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBedConfig> CompanyBedConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ekit> Ekits { get; set; }
        public virtual Facility Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseShift> NurseShifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseStationHierarchy> NurseStationHierarchies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingFrequencyConfig> NursingFrequencyConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingSchedule> NursingSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSubstanceCount> ControlSubstanceCounts { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRDCMailConfig> tblRDCMailConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleFacilityConfig> UserRoleFacilityConfigs { get; set; }
        public virtual PhysicianDetail PhysicianDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianDetail> PhysicianDetails { get; set; }
    }
}
