//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseCommentType
    {
        public int NurseCommentType_Id { get; set; }
        public string NurseCommentType_Desc { get; set; }
        public Nullable<int> NurseCommentType_Status { get; set; }
        public Nullable<int> NurseCommentType_CreatedBy { get; set; }
        public System.DateTime NurseCommentType_CreatedOn { get; set; }
    }
}
