//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NursingFCTime
    {
        public long FCTime_Id { get; set; }
        public Nullable<int> NursingFreq_Id { get; set; }
        public Nullable<int> hour_Id { get; set; }
    
        public virtual Hour Hour { get; set; }
        public virtual NursingFrequencyConfig NursingFrequencyConfig { get; set; }
    }
}
