//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseShift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NurseShift()
        {
            this.DrugAdministers = new HashSet<DrugAdminister>();
        }
    
        public int NurseShifts_Id { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
        public string NurseShifts_Name { get; set; }
        public Nullable<int> Fromtime_hoursId { get; set; }
        public Nullable<int> FromTime_TimeFormatId { get; set; }
        public Nullable<int> Totime_hoursId { get; set; }
        public Nullable<int> ToTime_TimeFormatId { get; set; }
        public Nullable<int> NurseShifts_Status { get; set; }
        public Nullable<int> NurseShifts_CreatedBy { get; set; }
        public Nullable<System.DateTime> NurseShifts_CreatedOn { get; set; }
    
        public virtual Hour Hour { get; set; }
        public virtual Hour Hour1 { get; set; }
        public virtual TimeFormat TimeFormat { get; set; }
        public virtual TimeFormat TimeFormat1 { get; set; }
        public virtual User User { get; set; }
        public virtual NursingStation NursingStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugAdminister> DrugAdministers { get; set; }
    }
}
