//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseStationHierarchy
    {
        public int NSHierarchy_Id { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
        public Nullable<int> FloorPrior { get; set; }
        public Nullable<int> WingPrior { get; set; }
        public Nullable<int> RoomPrior { get; set; }
        public Nullable<int> BedPrior { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
