//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseComment
    {
        public long Comments_Id { get; set; }
        public Nullable<long> DrugAdminister_Id { get; set; }
        public Nullable<int> NurseCommentType_Id { get; set; }
        public string Comment { get; set; }
        public Nullable<int> comment_Status { get; set; }
        public Nullable<int> comment_CreatedBy { get; set; }
        public System.DateTime Comment_CreatedOn { get; set; }
        public Nullable<int> PQuantity_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual QuantityDetail QuantityDetail { get; set; }
        public virtual DrugAdminister DrugAdminister { get; set; }
    }
}
