//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NursingSchedule
    {
        public int NursingSchedule_Id { get; set; }
        public int NursingStation_Id { get; set; }
        public string ScheduleTime { get; set; }
        public int NursingSchedule_Status { get; set; }
        public Nullable<int> NursingSchedule_CreatedBy { get; set; }
        public Nullable<System.DateTime> NursingSchedule_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
