//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observation
    {
        public int PObs_Id { get; set; }
        public int Patient_Id { get; set; }
        public string ValueType { get; set; }
        public string ObservationId { get; set; }
        public string ObservationText { get; set; }
        public string ObsCodingSystem { get; set; }
        public string OAlternateId { get; set; }
        public string OAlternateText { get; set; }
        public string OACodingSystem { get; set; }
        public string ObservationSubId { get; set; }
        public string ObservationValue { get; set; }
        public string UnitsId { get; set; }
        public string UnitText { get; set; }
        public string UnitCodingSystem { get; set; }
        public string UAlternateId { get; set; }
        public string UAlternateText { get; set; }
        public string UACodingSystem { get; set; }
        public string ReferenceRange { get; set; }
        public string AbnormalFlags { get; set; }
        public string Probability { get; set; }
        public string NatureOfAbnormalTest { get; set; }
        public string ObservationResultStatus { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string AccessChecks { get; set; }
        public Nullable<System.DateTime> ObservationDate { get; set; }
        public string ProducerID { get; set; }
        public string ProducerText { get; set; }
        public string ProducerCodingSystem { get; set; }
        public string PAlternateId { get; set; }
        public string PAlternateText { get; set; }
        public string PACodingSystem { get; set; }
        public string ResponsibleObserver { get; set; }
        public string ObservationMethod { get; set; }
        public string EquipmentInstance { get; set; }
        public Nullable<System.DateTime> AnalysisDate { get; set; }
        public int PObs_Status { get; set; }
        public Nullable<int> PObs_CreatedBy { get; set; }
        public Nullable<System.DateTime> PObs_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Demographic Demographic { get; set; }
    }
}
