//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnLeave
    {
        public int Onleave_Id { get; set; }
        public Nullable<long> PVisit_Id { get; set; }
        public Nullable<System.DateTime> LeaveFrom { get; set; }
        public Nullable<System.DateTime> LeaveTo { get; set; }
        public string Reason { get; set; }
        public Nullable<int> OnLeave_Status { get; set; }
        public Nullable<int> OnLeave_CreatedBy { get; set; }
        public System.DateTime OnLeave_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual VisitInfo VisitInfo { get; set; }
    }
}
