//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFavConfig
    {
        public int OFConfig_Id { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public string OrderFavCode { get; set; }
        public Nullable<int> OrderFavMaster_ID { get; set; }
        public Nullable<int> OFConfig_Status { get; set; }
        public Nullable<int> OFConfig_CreatedBy { get; set; }
        public Nullable<System.DateTime> OFConfig_CreatedDate { get; set; }
    }
}
