//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFavourite
    {
        public int OrderFavourite_ID { get; set; }
        public int PQuantity_Id { get; set; }
        public int OrderFavMaster_ID { get; set; }
        public int OrderFavourite_Status { get; set; }
        public Nullable<int> OrderFavourite_Createby { get; set; }
        public System.DateTime OrderFavourite_CreatedOn { get; set; }
    
        public virtual OrderFavouriteMaster OrderFavouriteMaster { get; set; }
        public virtual User User { get; set; }
        public virtual QuantityDetail QuantityDetail { get; set; }
    }
}
