//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderControlMaster
    {
        public int OrderControl_ID { get; set; }
        public string OrderControlValue { get; set; }
        public string OrderControlDesc { get; set; }
        public Nullable<int> OrderControlStatus { get; set; }
        public Nullable<int> OrderControlCretedBy { get; set; }
        public Nullable<System.DateTime> OrderControlCreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
