//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInactiveReason
    {
        public int OIAReason_Id { get; set; }
        public string OIAReason_Type { get; set; }
        public Nullable<int> OIAReason_Status { get; set; }
        public Nullable<int> OIAReason_CreatedBy { get; set; }
        public Nullable<System.DateTime> OIAReason_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
