//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderStock()
        {
            this.OrderStockTrans = new HashSet<OrderStockTran>();
        }
    
        public int OrderStock_Id { get; set; }
        public Nullable<int> Stock_Id { get; set; }
        public Nullable<int> Porder_Id { get; set; }
        public string Inhand { get; set; }
        public string Remaining { get; set; }
        public Nullable<int> OrderStock_Status { get; set; }
        public Nullable<int> OrderStock_CreatedBy { get; set; }
        public Nullable<System.DateTime> OrderStock_CreatedDate { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> PQuantity_Id { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStockTran> OrderStockTrans { get; set; }
    }
}
