//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStockTran
    {
        public int TransOS_Id { get; set; }
        public Nullable<int> OrderStock_Id { get; set; }
        public string Inhand { get; set; }
        public Nullable<int> TransOS_CreatedBy { get; set; }
        public int TransOS_Status { get; set; }
        public System.DateTime TransOS_CreatedDate { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual OrderStock OrderStock { get; set; }
    }
}
