//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderType
    {
        public int OrderTypeID { get; set; }
        public string OrderType_Desc { get; set; }
        public int OrderType_Status { get; set; }
        public Nullable<int> OrderType_CreatedBy { get; set; }
        public System.DateTime OrderType_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
