//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFavouriteMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderFavouriteMaster()
        {
            this.OrderFavouriteDatas = new HashSet<OrderFavouriteData>();
            this.OrderFavourites = new HashSet<OrderFavourite>();
        }
    
        public int OrderFavMaster_ID { get; set; }
        public string OrderFavDesc { get; set; }
        public int OrderFavMaster_status { get; set; }
        public Nullable<int> OrderFavMaster_CreatedBy { get; set; }
        public System.DateTime OrderFavMaster_CreatedOn { get; set; }
        public string OrderFavCode { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFavouriteData> OrderFavouriteDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFavourite> OrderFavourites { get; set; }
    }
}
