//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHold
    {
        public int OrderHold_Id { get; set; }
        public Nullable<int> PQuantity_Id { get; set; }
        public Nullable<System.DateTime> HoldFrom { get; set; }
        public Nullable<System.DateTime> HoldTo { get; set; }
        public string HoldReason { get; set; }
        public int OrderHold_Status { get; set; }
        public Nullable<int> OrderHold_CreatedBy { get; set; }
        public Nullable<System.DateTime> OrderHold_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual QuantityDetail QuantityDetail { get; set; }
    }
}
