//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFavouriteData
    {
        public long FavouriteData_Id { get; set; }
        public Nullable<long> DrugAdminister_Id { get; set; }
        public Nullable<int> OrderFavMaster_ID { get; set; }
        public string value { get; set; }
        public Nullable<int> FavouriteData_Status { get; set; }
        public Nullable<int> FavouriteData_CreatedBy { get; set; }
        public System.DateTime Favourite_CreatedOn { get; set; }
    
        public virtual OrderFavouriteMaster OrderFavouriteMaster { get; set; }
        public virtual User User { get; set; }
        public virtual OrderFavouriteData OrderFavouriteData1 { get; set; }
        public virtual OrderFavouriteData OrderFavouriteData2 { get; set; }
    }
}
