//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int Participant_Id { get; set; }
        public Nullable<int> Conversation_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Participant_Type { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual User2 User { get; set; }
    }
}
