//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientType()
        {
            this.ColourTypes = new HashSet<ColourType>();
            this.Demographics = new HashSet<Demographic>();
        }
    
        public int PatientType_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string Color_Code { get; set; }
        public string Color_Description { get; set; }
        public Nullable<int> PatientType_Status { get; set; }
        public Nullable<int> PatientType_CreatedBy { get; set; }
        public Nullable<System.DateTime> PatientType_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColourType> ColourTypes { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demographic> Demographics { get; set; }
    }
}
