//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCertifyOrder
    {
        public long PCertify_ID { get; set; }
        public Nullable<int> PCertifyTime_ID { get; set; }
        public Nullable<int> PPorder_Id { get; set; }
        public Nullable<int> Pmonths { get; set; }
        public Nullable<int> Pstatus { get; set; }
        public Nullable<System.DateTime> PCreatedDate { get; set; }
    }
}
