//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCertifyDate
    {
        public int PCertifyTime_ID { get; set; }
        public Nullable<System.DateTime> PCertifyDate1 { get; set; }
        public Nullable<int> PUser_Id { get; set; }
        public Nullable<int> PStatus { get; set; }
    }
}
