//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhysicianDetail()
        {
            this.CompanyConfigs = new HashSet<CompanyConfig>();
            this.NursingStations = new HashSet<NursingStation>();
        }
    
        public int Physician_Id { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
        public string PhysicianNPI { get; set; }
        public string PhysicianDEANumber { get; set; }
        public string PhysicianLName { get; set; }
        public string PhysicianFName { get; set; }
        public string PhysicianAddress1 { get; set; }
        public string PhysicianAddress2 { get; set; }
        public string PhysicianCity { get; set; }
        public string PhysicianState { get; set; }
        public string PhysicianZip { get; set; }
        public Nullable<int> PhysicianCountryID { get; set; }
        public int Physician_Status { get; set; }
        public Nullable<int> Physician_CreatedBy { get; set; }
        public System.DateTime Physician_CreatedDate { get; set; }
        public string PhysicianCredentials { get; set; }
        public Nullable<int> Credentials { get; set; }
        public string SupervisingPhy { get; set; }
        public string Physician_Phone { get; set; }
        public Nullable<int> PrimarySpec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyConfig> CompanyConfigs { get; set; }
        public virtual Facility Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingStation> NursingStations { get; set; }
        public virtual NursingStation NursingStation { get; set; }
        public virtual User User { get; set; }
    }
}
