//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessKeyMaster
    {
        public int ProcessID { get; set; }
        public string ProcessKey { get; set; }
        public string ComputerName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ProcessID_CreatedBy { get; set; }
        public Nullable<System.DateTime> ProcessID_CreatedOn { get; set; }
        public Nullable<int> NursingStation_Id { get; set; }
    }
}
