//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityDetail1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuantityDetail1()
        {
            this.NurseComments = new HashSet<NurseComment>();
            this.OrderDestroys = new HashSet<OrderDestroy>();
            this.OrderFavourites = new HashSet<OrderFavourite>();
            this.OrderHolds = new HashSet<OrderHold>();
        }
    
        public int PQuantity_Id { get; set; }
        public int POrder_Id { get; set; }
        public string Quantity { get; set; }
        public string RepeatPattern { get; set; }
        public string ExplicitTime { get; set; }
        public string RelativeTimeUnits { get; set; }
        public string ServiceDuration { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Priority { get; set; }
        public string ConditionText { get; set; }
        public string TextInstruction { get; set; }
        public string Conjunction { get; set; }
        public string OccuranceDuration { get; set; }
        public string TotalOccurances { get; set; }
        public int PQuantity_Status { get; set; }
        public Nullable<int> PQuantity_CreatedBy { get; set; }
        public System.DateTime PQuantity_CreatedDate { get; set; }
        public Nullable<int> EndDateStatus { get; set; }
        public Nullable<bool> PRNFlag { get; set; }
        public Nullable<int> ReviewFlag { get; set; }
        public string AlertText { get; set; }
        public Nullable<decimal> MaxPerdays { get; set; }
        public Nullable<bool> SelfAdministeredFlag { get; set; }
        public Nullable<bool> TreatmentFlag { get; set; }
        public string InsulinComments { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> DiscontinueFlag { get; set; }
        public string DiscontinueReason { get; set; }
    
        public virtual User User { get; set; }
        public virtual CommonOrderInfo CommonOrderInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseComment> NurseComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDestroy> OrderDestroys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFavourite> OrderFavourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHold> OrderHolds { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
