//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecentFac
    {
        public int RecFac_Id { get; set; }
        public int User_Id { get; set; }
        public int Facility_Id { get; set; }
        public string NurseStation_Id { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual User User { get; set; }
    }
}
