//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentOrder
    {
        public int ResOrder_Id { get; set; }
        public int Patient_ID { get; set; }
        public string ResOrderType { get; set; }
        public Nullable<System.DateTime> ResOrderDate { get; set; }
        public string ResPhysician { get; set; }
        public string ResOrderText { get; set; }
        public int ResOrder_Status { get; set; }
        public Nullable<int> ResOrder_CreatedBy { get; set; }
        public System.DateTime ResOrder_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Demographic Demographic { get; set; }
    }
}
