//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.RoleConfigs = new HashSet<RoleConfig>();
            this.UserRoleFacilityConfigs = new HashSet<UserRoleFacilityConfig>();
            this.UserSessions = new HashSet<UserSession>();
        }
    
        public int Role_Id { get; set; }
        public string Role_Desc { get; set; }
        public Nullable<int> DefaultScreen_Id { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public int Role_Status { get; set; }
        public Nullable<int> Role_CreatedBy { get; set; }
        public System.DateTime Role_CreatedDate { get; set; }
        public Nullable<int> Parent_Id { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleConfig> RoleConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleFacilityConfig> UserRoleFacilityConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSessions { get; set; }
        public virtual DefaultScreen DefaultScreen { get; set; }
    }
}
