//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleConfig
    {
        public int RoleConfig_Id { get; set; }
        public int Role_Id { get; set; }
        public Nullable<int> Screen_Id { get; set; }
        public Nullable<int> AccessRead { get; set; }
        public Nullable<int> AccessWrite { get; set; }
        public Nullable<int> PrintPdf { get; set; }
        public Nullable<int> PrintExcel { get; set; }
        public int RoleConfig_Status { get; set; }
        public Nullable<int> RoleConfig_CreatedBy { get; set; }
        public System.DateTime RoleConfig_CreatedDate { get; set; }
    
        public virtual Screen Screen { get; set; }
        public virtual User User { get; set; }
        public virtual Role Role { get; set; }
    }
}
