//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.CompanyBedConfigs = new HashSet<CompanyBedConfig>();
        }
    
        public int Room_Id { get; set; }
        public string Room_Name { get; set; }
        public string Room_Code { get; set; }
        public int Room_Status { get; set; }
        public Nullable<int> Room_CreatedBy { get; set; }
        public System.DateTime Room_CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBedConfig> CompanyBedConfigs { get; set; }
        public virtual User User { get; set; }
    }
}
