//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Route_Id { get; set; }
        public string Route_Code { get; set; }
        public string Route_Desc { get; set; }
        public Nullable<int> Route_Status { get; set; }
        public Nullable<int> Route_CreatedBy { get; set; }
        public Nullable<System.DateTime> Route_CreatedOn { get; set; }
        public string Route_DirDesc { get; set; }
    
        public virtual User User { get; set; }
    }
}
