//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Screen()
        {
            this.RoleConfigs = new HashSet<RoleConfig>();
            this.UserActivityDetails = new HashSet<UserActivityDetail>();
            this.DefaultScreens = new HashSet<DefaultScreen>();
        }
    
        public int Screen_Id { get; set; }
        public string Screen_Desc { get; set; }
        public Nullable<int> Screen_Order { get; set; }
        public int Screen_Status { get; set; }
        public Nullable<int> Screen_CreatedBy { get; set; }
        public System.DateTime Screen_CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleConfig> RoleConfigs { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserActivityDetail> UserActivityDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefaultScreen> DefaultScreens { get; set; }
    }
}
