//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.BarcodeDetails = new HashSet<BarcodeDetail>();
        }
    
        public int Stock_Id { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
        public string DrugName { get; set; }
        public string InHand { get; set; }
        public Nullable<int> Stock_Status { get; set; }
        public Nullable<int> Stock_CreatedBy { get; set; }
        public Nullable<System.DateTime> Stock_CreatedDate { get; set; }
        public string GPICode { get; set; }
        public Nullable<int> TrackableBit { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public Nullable<int> Sharedstockbit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarcodeDetail> BarcodeDetails { get; set; }
        public virtual User User { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
