//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockReport()
        {
            this.CompanyConfigs = new HashSet<CompanyConfig>();
        }
    
        public int StockReport_Id { get; set; }
        public string StockReportFor { get; set; }
        public Nullable<int> StockReport_Status { get; set; }
        public Nullable<int> StockReport_CreatedBy { get; set; }
        public System.DateTime StockReport_CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyConfig> CompanyConfigs { get; set; }
    }
}
