//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suffix
    {
        public int Suffix_Id { get; set; }
        public string Suffix_Desc { get; set; }
        public int Suffix_Status { get; set; }
        public Nullable<int> Suffix_CreatedBy { get; set; }
        public System.DateTime Suffix_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
