//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdministeredSite
    {
        public long ASites_Id { get; set; }
        public Nullable<long> DAdmin_Id { get; set; }
        public string Route { get; set; }
        public Nullable<int> Site_Id { get; set; }
        public Nullable<System.DateTime> AdministeredDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> DrugAdminister_Id { get; set; }
    }
}
