//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRDCMailConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRDCMailConfig()
        {
            this.tblRdcMailTimes = new HashSet<tblRdcMailTime>();
        }
    
        public int Rdc_Id { get; set; }
        public Nullable<int> Facility_Id { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
        public string MailTo { get; set; }
        public string MailCC { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Facility Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRdcMailTime> tblRdcMailTimes { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
