//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRdcMailTime
    {
        public int RdcTime_Id { get; set; }
        public Nullable<int> Rdc_Id { get; set; }
        public Nullable<int> Time_Id { get; set; }
    
        public virtual tblRDCMailConfig tblRDCMailConfig { get; set; }
    }
}
