//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmptblSegmentCheck
    {
        public long Segmentcheck_Id { get; set; }
        public Nullable<int> FileId { get; set; }
        public string SegmentCode { get; set; }
        public string SegmentValue { get; set; }
        public string SegmentDesc { get; set; }
        public Nullable<int> SegError { get; set; }
    }
}
