//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentDispenseInfo
    {
        public int PDispense_Id { get; set; }
        public int POrder_Id { get; set; }
        public string DispenseCounter { get; set; }
        public string DispenseCodeID { get; set; }
        public string DispenseCodeText { get; set; }
        public string ADispenseCodeID { get; set; }
        public Nullable<System.DateTime> DispensedDate { get; set; }
        public string ActualDispenseAmt { get; set; }
        public string ActualDispenseUnits { get; set; }
        public string ActualDosageForm { get; set; }
        public string PrescriptionNumber { get; set; }
        public string NumberOfRefillsRemaining { get; set; }
        public string DispenseNotes { get; set; }
        public string DispensingProvider { get; set; }
        public string SubstitutionStatus { get; set; }
        public string TotalDailyDose { get; set; }
        public string DispenseToLocation { get; set; }
        public string NeedsHumanReview { get; set; }
        public string SpecialDispensingInstruction { get; set; }
        public string ActualStrength { get; set; }
        public string ActualStrengthUnit { get; set; }
        public string SubstanceLotNumber { get; set; }
        public Nullable<System.DateTime> SubstanceExpirationDate { get; set; }
        public string SubstanceManufacturer { get; set; }
        public string Indication { get; set; }
        public string DispensePackageSize { get; set; }
        public string DispensePackageSizeUnits { get; set; }
        public string DispensePackageMethod { get; set; }
        public string SupplementaryCode { get; set; }
        public string InitiatingLocation { get; set; }
        public string AssemblyLocation { get; set; }
        public string ActualDrugStrengthVolume { get; set; }
        public string ActualDrugStrengthVolUnits { get; set; }
        public string DispenseToPharmacy { get; set; }
        public string DispenseToPharmacyAddress { get; set; }
        public string PharmacyOrderType { get; set; }
        public string DispenceType { get; set; }
        public int PDispense_Status { get; set; }
        public Nullable<int> PDispense_CreatedBy { get; set; }
        public System.DateTime PDispense_CreatedDate { get; set; }
        public Nullable<int> PTOutBoundFileStatus { get; set; }
        public Nullable<int> PTOutBoundApproval { get; set; }
        public Nullable<int> PTOutBoundApprovalBy { get; set; }
        public Nullable<System.DateTime> PTOutBoundApprovalOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual CommonOrderInfo CommonOrderInfo { get; set; }
    }
}
