//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentRouteInfo
    {
        public int PRoute_Id { get; set; }
        public int POrder_Id { get; set; }
        public string RouteCode { get; set; }
        public string RouteText { get; set; }
        public string AdministrationSite { get; set; }
        public string AdministrationDevice { get; set; }
        public string AdministrationMethod { get; set; }
        public string RoutingInstruction { get; set; }
        public string AdminstrationSiteModifier { get; set; }
        public int PRoute_Status { get; set; }
        public Nullable<int> PRoute_CreatedBy { get; set; }
        public System.DateTime PRoute_CreatedDate { get; set; }
        public Nullable<int> PTROutBoundFileStatus { get; set; }
        public Nullable<int> PTROutBoundApproval { get; set; }
        public Nullable<int> PTROutBoundApprovalBy { get; set; }
        public Nullable<System.DateTime> PTROutBoundApprovalOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual CommonOrderInfo CommonOrderInfo { get; set; }
    }
}
