//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedDocument
    {
        public int PatientDoc_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public string DocName { get; set; }
        public string DocLocation { get; set; }
        public string DocDescription { get; set; }
        public Nullable<int> FolderID { get; set; }
        public Nullable<System.DateTime> UDocuments_CreatedDate { get; set; }
        public Nullable<int> UDocuments_CreatedBy { get; set; }
        public string DocType { get; set; }
    
        public virtual User User { get; set; }
    }
}
