//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityDetail
    {
        public long UserActivity_Id { get; set; }
        public Nullable<long> Session_Id { get; set; }
        public Nullable<int> Screen_Id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Activity_Id { get; set; }
        public string Comments { get; set; }
    
        public virtual ActivityMaster ActivityMaster { get; set; }
        public virtual Screen Screen { get; set; }
        public virtual UserSession UserSession { get; set; }
    }
}
