//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleFacilityConfig
    {
        public int UserRole_Id { get; set; }
        public int Role_ID { get; set; }
        public int User_Id { get; set; }
        public int Facility_id { get; set; }
        public int UserRole_Status { get; set; }
        public Nullable<int> UserRole_CreatedBy { get; set; }
        public System.DateTime UserRole_CreatedDate { get; set; }
        public Nullable<int> NurseStation_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Role Role { get; set; }
        public virtual NursingStation NursingStation { get; set; }
    }
}
