//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AllergyTypeCodes = new HashSet<AllergyTypeCode>();
            this.ApiIntegrations = new HashSet<ApiIntegration>();
            this.Beds = new HashSet<Bed>();
            this.BehavioralSymptomsMasters = new HashSet<BehavioralSymptomsMaster>();
            this.ClassDrugCodingTypes = new HashSet<ClassDrugCodingType>();
            this.CompanyBedConfigs = new HashSet<CompanyBedConfig>();
            this.Countries = new HashSet<Country>();
            this.DiagnosisCodingTypes = new HashSet<DiagnosisCodingType>();
            this.DocFolders = new HashSet<DocFolder>();
            this.EventCategories = new HashSet<EventCategory>();
            this.FileAckInformations = new HashSet<FileAckInformation>();
            this.FileInformations = new HashSet<FileInformation>();
            this.Floors = new HashSet<Floor>();
            this.FrequencyMasters = new HashSet<FrequencyMaster>();
            this.FTECategories = new HashSet<FTECategory>();
            this.FteConnections = new HashSet<FteConnection>();
            this.Genders = new HashSet<Gender>();
            this.HLSevenCompanyConfigs = new HashSet<HLSevenCompanyConfig>();
            this.HLSevenSegmentDetails = new HashSet<HLSevenSegmentDetail>();
            this.HLSevenSegments = new HashSet<HLSevenSegment>();
            this.Hours = new HashSet<Hour>();
            this.ICD10 = new HashSet<ICD10>();
            this.ImportFiles = new HashSet<ImportFile>();
            this.IntegrationTypes = new HashSet<IntegrationType>();
            this.MaritalStatus = new HashSet<MaritalStatu>();
            this.MedicationReasons = new HashSet<MedicationReason>();
            this.Months = new HashSet<Month>();
            this.NursingSchedules = new HashSet<NursingSchedule>();
            this.OrderControlMasters = new HashSet<OrderControlMaster>();
            this.OrderFavouriteMasters = new HashSet<OrderFavouriteMaster>();
            this.OrderTypes = new HashSet<OrderType>();
            this.RoleConfigs = new HashSet<RoleConfig>();
            this.Rooms = new HashSet<Room>();
            this.Screens = new HashSet<Screen>();
            this.Suffixes = new HashSet<Suffix>();
            this.TimeFormats = new HashSet<TimeFormat>();
            this.AddlInstructionDetails = new HashSet<AddlInstructionDetail>();
            this.AncillaryDetails = new HashSet<AncillaryDetail>();
            this.AncillaryDetails1 = new HashSet<AncillaryDetail>();
            this.CompoundOrders = new HashSet<CompoundOrder>();
            this.CompoundOrders1 = new HashSet<CompoundOrder>();
            this.InsuranceInfoes = new HashSet<InsuranceInfo>();
            this.NotesInfoes = new HashSet<NotesInfo>();
            this.Observations = new HashSet<Observation>();
            this.OutBoundFileInformations = new HashSet<OutBoundFileInformation>();
            this.ResidentOrders = new HashSet<ResidentOrder>();
            this.TreatmentInfoes = new HashSet<TreatmentInfo>();
            this.TreatmentInfoes1 = new HashSet<TreatmentInfo>();
            this.User1 = new HashSet<User>();
            this.UserRoleFacilityConfigs = new HashSet<UserRoleFacilityConfig>();
            this.UserRoleFacilityConfigs1 = new HashSet<UserRoleFacilityConfig>();
            this.VisitBehaviours = new HashSet<VisitBehaviour>();
            this.VisitFoodintakes = new HashSet<VisitFoodintake>();
            this.VisitInfoes = new HashSet<VisitInfo>();
            this.VisitInfoes1 = new HashSet<VisitInfo>();
            this.VisitNursingNotes = new HashSet<VisitNursingNote>();
            this.VisitVitals = new HashSet<VisitVital>();
            this.WeekDays = new HashSet<WeekDay>();
            this.Weeks = new HashSet<Week>();
            this.Wings = new HashSet<Wing>();
            this.AllergyInfoes = new HashSet<AllergyInfo>();
            this.AllergyInfoes1 = new HashSet<AllergyInfo>();
            this.DiagnosisInfoes = new HashSet<DiagnosisInfo>();
            this.DiagnosisInfoes1 = new HashSet<DiagnosisInfo>();
            this.MailConfigs = new HashSet<MailConfig>();
            this.OrderDestroys = new HashSet<OrderDestroy>();
            this.OrderDestroys1 = new HashSet<OrderDestroy>();
            this.OrderDestroys2 = new HashSet<OrderDestroy>();
            this.ApprovalAllergyInfoes = new HashSet<ApprovalAllergyInfo>();
            this.ApprovalAllergyInfoes1 = new HashSet<ApprovalAllergyInfo>();
            this.ApprovalDiagnosisInfoes = new HashSet<ApprovalDiagnosisInfo>();
            this.ApprovalDiagnosisInfoes1 = new HashSet<ApprovalDiagnosisInfo>();
            this.ApprovalVisitInfoes = new HashSet<ApprovalVisitInfo>();
            this.ApprovalVisitInfoes1 = new HashSet<ApprovalVisitInfo>();
            this.ControlSubstanceCounts = new HashSet<ControlSubstanceCount>();
            this.ControlSubstanceCounts1 = new HashSet<ControlSubstanceCount>();
            this.UploadedDocuments = new HashSet<UploadedDocument>();
            this.AllergyInfoMasters = new HashSet<AllergyInfoMaster>();
            this.ActivityMasters = new HashSet<ActivityMaster>();
            this.UserSessions = new HashSet<UserSession>();
            this.OrderFavouriteDatas = new HashSet<OrderFavouriteData>();
            this.NurseComments = new HashSet<NurseComment>();
            this.PatientTypes = new HashSet<PatientType>();
            this.ColourTypes = new HashSet<ColourType>();
            this.Fingersdescs = new HashSet<Fingersdesc>();
            this.BarcodeDetails = new HashSet<BarcodeDetail>();
            this.MailFavourites = new HashSet<MailFavourite>();
            this.MailReads = new HashSet<MailRead>();
            this.AlertStatus = new HashSet<AlertStatu>();
            this.Routes = new HashSet<Route>();
            this.Ekits = new HashSet<Ekit>();
            this.Stocks = new HashSet<Stock>();
            this.Drugs = new HashSet<Drug>();
            this.EkitAdministers = new HashSet<EkitAdminister>();
            this.NurseShifts = new HashSet<NurseShift>();
            this.CompanyConfigs = new HashSet<CompanyConfig>();
            this.HLDirectionalWays = new HashSet<HLDirectionalWay>();
            this.OnLeaves = new HashSet<OnLeave>();
            this.NursingFrequencyConfigs = new HashSet<NursingFrequencyConfig>();
            this.Roles = new HashSet<Role>();
            this.DefaultScreens = new HashSet<DefaultScreen>();
            this.ApprovalDemographics = new HashSet<ApprovalDemographic>();
            this.ApprovalDemographics1 = new HashSet<ApprovalDemographic>();
            this.Companies = new HashSet<Company>();
            this.Facilities = new HashSet<Facility>();
            this.FTEConfigurations = new HashSet<FTEConfiguration>();
            this.RecentFacs = new HashSet<RecentFac>();
            this.OrderStocks = new HashSet<OrderStock>();
            this.HLSevenOutboundDisplayCompanyConfigs = new HashSet<HLSevenOutboundDisplayCompanyConfig>();
            this.HLSevenOutboundDisplaySegmentDetails = new HashSet<HLSevenOutboundDisplaySegmentDetail>();
            this.HLSevenOutboundDisplaySegments = new HashSet<HLSevenOutboundDisplaySegment>();
            this.DocAdministerTrans = new HashSet<DocAdministerTran>();
            this.OrderFavourites = new HashSet<OrderFavourite>();
            this.OrderHolds = new HashSet<OrderHold>();
            this.TreatmentDispenseInfoes = new HashSet<TreatmentDispenseInfo>();
            this.TreatmentDispenseInfoes1 = new HashSet<TreatmentDispenseInfo>();
            this.TreatmentRouteInfoes = new HashSet<TreatmentRouteInfo>();
            this.TreatmentRouteInfoes1 = new HashSet<TreatmentRouteInfo>();
            this.OrderInactiveReasons = new HashSet<OrderInactiveReason>();
            this.NurseStationHierarchies = new HashSet<NurseStationHierarchy>();
            this.ControlSubstanceTrans = new HashSet<ControlSubstanceTran>();
            this.ControlSubstanceTrans1 = new HashSet<ControlSubstanceTran>();
            this.OrderStockTrans = new HashSet<OrderStockTran>();
            this.ControlSubstanceReasons = new HashSet<ControlSubstanceReason>();
            this.EkitControlSubstanceReasons = new HashSet<EkitControlSubstanceReason>();
            this.EKitControlSubstanceTrans = new HashSet<EKitControlSubstanceTran>();
            this.EKitControlSubstanceTrans1 = new HashSet<EKitControlSubstanceTran>();
            this.WeightLogs = new HashSet<WeightLog>();
            this.Demographics = new HashSet<Demographic>();
            this.Demographics1 = new HashSet<Demographic>();
            this.QuantityDetails = new HashSet<QuantityDetail>();
            this.NursingStations = new HashSet<NursingStation>();
            this.PhysicianDetails = new HashSet<PhysicianDetail>();
            this.CommonOrderInfoes = new HashSet<CommonOrderInfo>();
            this.CommonOrderInfoes1 = new HashSet<CommonOrderInfo>();
            this.ApprovalOrders = new HashSet<ApprovalOrder>();
            this.ApprovalOrders1 = new HashSet<ApprovalOrder>();
            this.EncodedOrderDetails = new HashSet<EncodedOrderDetail>();
            this.EncodedOrderDetails1 = new HashSet<EncodedOrderDetail>();
            this.DrugAdministers = new HashSet<DrugAdminister>();
            this.DrugAdministers1 = new HashSet<DrugAdminister>();
            this.DrugAdministers2 = new HashSet<DrugAdminister>();
            this.DrugAdministers3 = new HashSet<DrugAdminister>();
        }
    
        public int User_Id { get; set; }
        public string User_Suffix { get; set; }
        public string User_Fname { get; set; }
        public string User_Lname { get; set; }
        public string User_Mname { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> User_Gender { get; set; }
        public Nullable<int> User_MaritalStatus { get; set; }
        public string User_DisplayName { get; set; }
        public string User_Email { get; set; }
        public string User_Phone { get; set; }
        public int User_PwdCount { get; set; }
        public int User_Lock { get; set; }
        public int User_Status { get; set; }
        public Nullable<int> User_CreatedBy { get; set; }
        public System.DateTime User_CreatedDate { get; set; }
        public string User_Token { get; set; }
        public Nullable<int> StkReportReq { get; set; }
        public Nullable<int> NewUserFlag { get; set; }
        public Nullable<int> ProcessKey { get; set; }
        public string PhysicianNPI { get; set; }
        public Nullable<int> PastDueAlertFlag { get; set; }
        public string User_ShortName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllergyTypeCode> AllergyTypeCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiIntegration> ApiIntegrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bed> Beds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehavioralSymptomsMaster> BehavioralSymptomsMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassDrugCodingType> ClassDrugCodingTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBedConfig> CompanyBedConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosisCodingType> DiagnosisCodingTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocFolder> DocFolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventCategory> EventCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileAckInformation> FileAckInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileInformation> FileInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Floor> Floors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrequencyMaster> FrequencyMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FTECategory> FTECategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FteConnection> FteConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gender> Genders { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenCompanyConfig> HLSevenCompanyConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenSegmentDetail> HLSevenSegmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenSegment> HLSevenSegments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hour> Hours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICD10> ICD10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportFile> ImportFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegrationType> IntegrationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaritalStatu> MaritalStatus { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicationReason> MedicationReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Month> Months { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingSchedule> NursingSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderControlMaster> OrderControlMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFavouriteMaster> OrderFavouriteMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderType> OrderTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleConfig> RoleConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Screen> Screens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suffix> Suffixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeFormat> TimeFormats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddlInstructionDetail> AddlInstructionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AncillaryDetail> AncillaryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AncillaryDetail> AncillaryDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompoundOrder> CompoundOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompoundOrder> CompoundOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceInfo> InsuranceInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesInfo> NotesInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observation> Observations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutBoundFileInformation> OutBoundFileInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentOrder> ResidentOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentInfo> TreatmentInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentInfo> TreatmentInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleFacilityConfig> UserRoleFacilityConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleFacilityConfig> UserRoleFacilityConfigs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitBehaviour> VisitBehaviours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitFoodintake> VisitFoodintakes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitInfo> VisitInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitInfo> VisitInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitNursingNote> VisitNursingNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitVital> VisitVitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeekDay> WeekDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Week> Weeks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wing> Wings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllergyInfo> AllergyInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllergyInfo> AllergyInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosisInfo> DiagnosisInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosisInfo> DiagnosisInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailConfig> MailConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDestroy> OrderDestroys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDestroy> OrderDestroys1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDestroy> OrderDestroys2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalAllergyInfo> ApprovalAllergyInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalAllergyInfo> ApprovalAllergyInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalDiagnosisInfo> ApprovalDiagnosisInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalDiagnosisInfo> ApprovalDiagnosisInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalVisitInfo> ApprovalVisitInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalVisitInfo> ApprovalVisitInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSubstanceCount> ControlSubstanceCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSubstanceCount> ControlSubstanceCounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedDocument> UploadedDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllergyInfoMaster> AllergyInfoMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityMaster> ActivityMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFavouriteData> OrderFavouriteDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseComment> NurseComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientType> PatientTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColourType> ColourTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fingersdesc> Fingersdescs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarcodeDetail> BarcodeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailFavourite> MailFavourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailRead> MailReads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertStatu> AlertStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ekit> Ekits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drug> Drugs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EkitAdminister> EkitAdministers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseShift> NurseShifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyConfig> CompanyConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLDirectionalWay> HLDirectionalWays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnLeave> OnLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingFrequencyConfig> NursingFrequencyConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefaultScreen> DefaultScreens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalDemographic> ApprovalDemographics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalDemographic> ApprovalDemographics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facility> Facilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FTEConfiguration> FTEConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecentFac> RecentFacs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStock> OrderStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenOutboundDisplayCompanyConfig> HLSevenOutboundDisplayCompanyConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenOutboundDisplaySegmentDetail> HLSevenOutboundDisplaySegmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HLSevenOutboundDisplaySegment> HLSevenOutboundDisplaySegments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocAdministerTran> DocAdministerTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFavourite> OrderFavourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHold> OrderHolds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentDispenseInfo> TreatmentDispenseInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentDispenseInfo> TreatmentDispenseInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentRouteInfo> TreatmentRouteInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentRouteInfo> TreatmentRouteInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInactiveReason> OrderInactiveReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseStationHierarchy> NurseStationHierarchies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSubstanceTran> ControlSubstanceTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSubstanceTran> ControlSubstanceTrans1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStockTran> OrderStockTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSubstanceReason> ControlSubstanceReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EkitControlSubstanceReason> EkitControlSubstanceReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EKitControlSubstanceTran> EKitControlSubstanceTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EKitControlSubstanceTran> EKitControlSubstanceTrans1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeightLog> WeightLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demographic> Demographics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demographic> Demographics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuantityDetail> QuantityDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingStation> NursingStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianDetail> PhysicianDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonOrderInfo> CommonOrderInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonOrderInfo> CommonOrderInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalOrder> ApprovalOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalOrder> ApprovalOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncodedOrderDetail> EncodedOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncodedOrderDetail> EncodedOrderDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugAdminister> DrugAdministers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugAdminister> DrugAdministers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugAdminister> DrugAdministers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugAdminister> DrugAdministers3 { get; set; }
    }
}
