//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOTP
    {
        public long TransID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string OTP { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<int> LoginType { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
