//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitBehaviour
    {
        public long VisitBehaviour_ID { get; set; }
        public long PVisit_Id { get; set; }
        public Nullable<int> HallucinationsID { get; set; }
        public Nullable<int> DelusionsID { get; set; }
        public Nullable<int> Physicalbehavioral { get; set; }
        public Nullable<int> Verbalbehavioral { get; set; }
        public Nullable<int> Otherbehavioral { get; set; }
        public Nullable<int> rejectevaluation { get; set; }
        public Nullable<int> Resisdentwandered { get; set; }
        public string Comments { get; set; }
        public string Initials { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> WeeklyStatus { get; set; }
        public int VisitBehaviour_Status { get; set; }
        public Nullable<int> VisitBehaviour_CreatedBy { get; set; }
        public System.DateTime VisitBehaviour_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual VisitInfo VisitInfo { get; set; }
    }
}
