//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitVital
    {
        public long Vitals_ID { get; set; }
        public long PVisit_Id { get; set; }
        public Nullable<System.DateTime> VitalDate { get; set; }
        public string VitalTime { get; set; }
        public string CistolicBP { get; set; }
        public Nullable<int> DiastolicBP { get; set; }
        public Nullable<int> HeartRate { get; set; }
        public Nullable<int> RespiratoryRate { get; set; }
        public Nullable<int> OxygenRate { get; set; }
        public string Temperature { get; set; }
        public string Pain { get; set; }
        public string Remark { get; set; }
        public Nullable<int> PulseRate { get; set; }
        public string Initials { get; set; }
        public string BloodSugar { get; set; }
        public string PDAID { get; set; }
        public int VitalSigns_status { get; set; }
        public Nullable<int> VitalSigns_CreatedBy { get; set; }
        public System.DateTime VitalSigns_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual VisitInfo VisitInfo { get; set; }
    }
}
