//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitNursingNote
    {
        public long VisitNursingNotes_ID { get; set; }
        public long PVisit_Id { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
        public string NoteTime { get; set; }
        public string NurseName { get; set; }
        public string Notes { get; set; }
        public string PDAID { get; set; }
        public int VisitNursingNotes_Status { get; set; }
        public Nullable<int> VisitNursingNotes_CreatedBy { get; set; }
        public System.DateTime VisitNursingNotes_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual VisitInfo VisitInfo { get; set; }
    }
}
