//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Week()
        {
            this.NursingFrequencyConfigs = new HashSet<NursingFrequencyConfig>();
        }
    
        public int Week_Id { get; set; }
        public string Week_Desc { get; set; }
        public int Week_Status { get; set; }
        public Nullable<int> Week_CreatedBy { get; set; }
        public System.DateTime Week_CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingFrequencyConfig> NursingFrequencyConfigs { get; set; }
    }
}
