//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekDay
    {
        public int Weekdays_ID { get; set; }
        public string Weekdays_Desc { get; set; }
        public int Weekdays_Status { get; set; }
        public Nullable<int> Weekdays_CreatedBy { get; set; }
        public System.DateTime Weekdays_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
