//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightLog
    {
        public int WeightLog_ID { get; set; }
        public int Patient_Id { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Type { get; set; }
        public string HeightFeet { get; set; }
        public string HeightInc { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> PreDialysis { get; set; }
        public Nullable<int> PostDialysis { get; set; }
        public string Remarks { get; set; }
        public string IBW { get; set; }
        public string initials { get; set; }
        public int WeightLog_Status { get; set; }
        public Nullable<int> WeightLog_CreatedBy { get; set; }
        public System.DateTime WeightLog_CreatedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual Demographic Demographic { get; set; }
    }
}
