//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wing()
        {
            this.CompanyBedConfigs = new HashSet<CompanyBedConfig>();
            this.NursingFrequencyConfigs = new HashSet<NursingFrequencyConfig>();
        }
    
        public int Wing_Id { get; set; }
        public string Wing_Desc { get; set; }
        public int Wing_Status { get; set; }
        public int Wing_CreatedBy { get; set; }
        public System.DateTime Wing_CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBedConfig> CompanyBedConfigs { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursingFrequencyConfig> NursingFrequencyConfigs { get; set; }
    }
}
