//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCPro.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class VisitFoodintakeEntity
    {
        public long VisitFoodintake_ID { get; set; }
        public long PVisit_Id { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public string Initials { get; set; }
        public string Attendingphysician { get; set; }
        public string Fluidsb { get; set; }
        public string Alternateb { get; set; }
        public string supplementb { get; set; }
        public string Fluidsl { get; set; }
        public string Alternatel { get; set; }
        public string supplementl { get; set; }
        public string Fluidss { get; set; }
        public string Alternates { get; set; }
        public string supplements { get; set; }
        public int VisitFoodintake_Status { get; set; }
        public Nullable<int> VisitFoodintake_CreatedBy { get; set; }
        public Nullable<System.DateTime> VisitFoodintake_CreatedDate { get; set; }
        public string UserName { get; set; }
       
    }
}
