export class ResidentDemographic {
    Patient_Id: number;
    PatientLastName: string;
    PatientFirstName: string;
    PatientMiddleInitial: string;
    PatientAddress1: string;
    PatientAddress2: string;
    PatientCity: string;
    PatientState: string;
    PatientZipCode: string;
    PhoneHome: string;
    ImageLocation: string;
    Patient_Status: number;
    Patient_CreatedBy: number;
    Patient_CreatedDate: string;
    PatientType_Id:number;
}

export class ResidentAdmitDischarge {
    PVisit_Id: number;
    Patient_Id: number;
    AdmitDate: string;
    DischargeDate: string;
    PVisit_Status: number;
    NoofDays: number;
}
export class DemographicInfo {
    Patient_Id: number;
    PatientLastName: string;
    PatientFirstName: string;
    PatientMiddleInitial: string;
    DOB: string;
    AdministrativeSex: string;
    PatientAddress1: string;
    PatientAddress2: string;
    PhoneHome: string;
    PatientMRNumber: string;
    SSN: string;
    Patient_Status: number;
    Patient_CreatedBy: number;
    Patient_CreatedDate: string;
    ImageLocation: string;
    PatientCity: string;
    PatientState: string;
    PatientZipcode: string;
    NurseStation_Name: string;
    WingId: number;
    FloorId: number;
    RoomId: number;
    BedId: number;
    HomeFlag: number;
    PVisit_Id: number;
    PVisit_Status: number;
    NursingStationId: number;
    FacilityId: number;
    AliasName:string;
    Pregnant:number;
    BreastFeeding:number;
}
export class Allergies {
    PAllergy_Id: number;
    Patient_Id: number;
    AllergyType_Id: number;
    ClassDrug_Id: number;
    ClassDrug_Name: string;
    ClassDrugType: number;
    NameOfCoding: string;
    AllergySeverityCode: string;
    AllergyReactionCode: string;
    AllergyIdentificationDate: string;
    PAllergy_Status: number;
    PAllergy_CreatedBy: number;
    PAllergy_CreatedDate: string;
    PAOutBoundFileStatus: number;
    PAOutBoundApproval: number;
    PAOutBoundApprovalBy: number;
    PAOutBoundApprovalOn: string;
}
export class Diagnosis {
    PDiagnosis_Id: number;
    Patient_Id: number;
    ICD10_Id: number;
    CodingMethod: string;
    DCodingType_Id: number;
    DiagnosisDescription: string;
    AltCodingId: string;
    AltCodingText: string;
    AltCodingMethod: string;
    DiagnosisType: string;
    MajorDiagnosticId: string;
    MajorDiagnosticText: string;
    MDCodingSystem: string;
    MDAlternateId: string;
    MDAlternateText: string;
    MDAltCodingSystem: string;
    DiagnosticGroupId: string;
    DiagnosticGroupText: string;
    DGCodingSystem: string;
    DGAlternateId: string;
    DGAlternateText: string;
    DGAltCodingSystem: string;
    DRGApprovalIndicator: string;
    DRGGrouperReviewCode: string;
    OutlierId: string;
    OutlierText: string;
    OutlierCodingSystem: string;
    OAlternateId: string;
    OAlternateText: string;
    OAltCodingSystem: string;
    OutlierDays: string;
    OutlierQuantity: string;
    OutlierDenomination: string;
    PriceType: string;
    FromValue: string;
    ToValue: string;
    RangeId: string;
    RangeText: string;
    RangeCodingSystem: string;
    RangeAltId: string;
    RangeAltText: string;
    RangeAltCodingSystem: string;
    RangeType: string;
    GrouperVersion: string;
    DiagnosisPriority: string;
    DiagnosisClassification: string;
    PDiagnosis_Status: number;
    DiagnosisDate: string;
    ConfidentialIndicator: string;
    AttestationDate: string;
    DiagnosisIdentifier: string;
    DiagnosisActionCode: string;
    PDiagnosis_CreatedBy: number;
    PDiagnosis_CreatedDate: string;
    PDGOutBoundFileStatus: number;
    PDGOutBoundApproval: number;
    PDGOutBoundApprovalBy: number;
    PDGOutBoundApprovalOn: string;
    ICD10_RawFormat: string;
    PhysicianNPI: string
    PhysicianLName: string
    PhysicianFName: string
}
export class UploadedDocuments {
    PatientDoc_Id: number;
    Patient_Id: number;
    DocName: string;
    DocType: string;
    DocLocation: string;
    DocDescription: string;
    FolderID: number;
    UDocuments_CreatedDate: string;
    UDocuments_CreatedBy: number;
}
export class LiteralOders {
    POrder_Id: number;
    Patient_Id: number;
    FillerType: string;
    OrderControl: string;
    FacilityId: string;
    PatientId: string;
    Room: string;
    TransactionDate: string;
    EnteredBy: string;
    VerifiedBy: string;
    VEffectivedate: string;
    OPhysicianLname: string;
    OPhysicianFname: string;
    OrderEffectiveDate: string;
    OrderingFacilityName: string;
    OrderingFacilityAddress1: string;
    OrderingFacilityPhone: string;
    GiveCodeText: string;
}

export class Medications {
    PTreatment_Id: number;
    Patient_Id: number;
    RequestedGiveCode: string;
    RequestedDosageForm: string;
    ProvidersTreatmentInstructions: string;
    // RequestedDispenseCode
    // RequestedDispenseAmount
    // RequestedDispenseUnits
    NumberOfRefills: string;
    OrderingProviderDEANumber: string;
    PTreatment_Status: number;
    PTreatment_CreatedBy: number;
    PTreatment_CreatedDate: string;
}

export class ApprovalEntity {
    ApprovalId: number;
    //Id column in respected table
    Record_Id: number;
    Patient_Id: number;
    Patient_Name: string;
    //Matching table
    Category: string;
    CategoryId: number;
    CreatedBy: number;
    CreatedDate: string;
    ApprovalStatus: number;
    ApprovedBy: number;
    ApprovedDate: string;
    UserName: string;
}
export class ResidentDemographicMaster {
    Patient_Id: number;
    ExternalPatientId: string;
    ExternalFacShortName: string;
    ExternalFacPatientId: string;
    AlternatePatientId: number;
    PatientLastName: string;
    PatientFirstName: string;
    PatientMiddleInitial: string;
    NameTypeCode: string;
    MotherMaidenName: string;
    DOB: string;
    AdministrativeSex: string;
    PatientAlias: string;
    Race: string;
    PatientAddress1: string;
    PatientAddress2: string;
    PatientCity: string;
    PatientState: string;
    PatientZipCode: string;
    CountyCode: string;
    PhoneHome: string;
    PhoneBusiness: string;
    PrimaryLanguage: string;
    MaritalStatus: string;
    Religion: string;
    PatientMRNumber: string;
    SSN: string;
    DriverLicense: string;
    MotherIdentifier: string;
    EthnicGroup: string;
    BirthPlace: string;
    MultipleBirthIndicator: string;
    BirthOrder: string;
    Citizenship: string;
    MilitaryStatus: string;
    Nationality: string;
    DeathDateTime: string;
    DeathIndicator: string;
    IdentityIndicator: string;
    IdentityReliability: string;
    LastUpdate: string;
    LastFacilityUpdate: string;
    SpeciesCode: string;
    BreedCode: string;
    Strain: string;
    ProductionClassCode: string;
    TribalCitizenship: string;
    ImageLocation: string;
    Patient_Status: number;
    Patient_CreatedBy: number;
    Patient_CreatedDate: string;
    PDOutBoundFileStatus: number;
    PDOutBoundApproval: number;
    PDOutBoundApprovalBy: number;
    PDOutBoundApprovalOn: string;
    Alert: string;
    Diet: string;
}
export class DemographicCustomInfo
{
    Patient_Id: number;
    ExternalPatientId: string;
    ExternalFacShortName: string;
    ExternalFacPatientId: string;
    AlternatePatientId: number;
    PatientLastName: string;
    PatientFirstName: string;
    PatientMiddleInitial: string;
    NameTypeCode: string;
    MotherMaidenName: string;
    DOB: string;
    AdministrativeSex: string;
    PatientAlias: string;
    Race: string;
    PatientAddress1: string;
    PatientAddress2: string;
    PatientCity: string;
    PatientState: string;
    PatientZipCode: string;
    CountyCode: string;
    PhoneHome: string;
    PhoneBusiness: string;
    PrimaryLanguage: string;
    MaritalStatus: string;
    Religion: string;
    PatientMRNumber: string;
    SSN: string;
    DriverLicense: string;
    MotherIdentifier: string;
    EthnicGroup: string;
    BirthPlace: string;
    MultipleBirthIndicator: string;
    BirthOrder: string;
    Citizenship: string;
    MilitaryStatus: string;
    Nationality: string;
    DeathDateTime: string;
    DeathIndicator: string;
    IdentityIndicator: string;
    IdentityReliability: string;
    LastUpdate: string;
    LastFacilityUpdate: string;
    SpeciesCode: string;
    BreedCode: string;
    Strain: string;
    ProductionClassCode: string;
    TribalCitizenship: string;
    ImageLocation: string;
    Patient_Status: number;
    Patient_CreatedBy: number;
    Patient_CreatedDate: string;
    PDOutBoundFileStatus: number;
    PDOutBoundApproval: number;
    PDOutBoundApprovalBy: number;
    PDOutBoundApprovalOn: string;
    Alert: string;
    Diet: string;
    ApprovalPatient_Id:number;
    BiometricInfo:string;
}
export class VisitInfoCuston
{
    PVisit_Id: number;
    Patient_Id: number;
    PatientClass: string;
    NursingStationId: string;
    Room: string;
    Bed: string;
    FacilityId: string;
    Floor: string;
    AdmissionType: string;
    PreAdmitNumber: string;
    PriorNursingStationId: string;
    PriorRoom: string;
    PriorBed: string;
    PriorFacilityId: string;
    PriorFloor: string;
    PrimaryPhysicianNPI: string;
    PrimaryPhysicianLName: string;
    PrimaryPhysicianFName: string;
    ReferringDoctor: string;
    ConsultingDoctor: string;
    HospitalService: string;
    TemporaryLocation: string;
    PreAdmitTestIndicator: string;
    ReAdmissionIndicator: string;
    AdmitSource: string;
    AmbulatoryStatus: string;
    VIPIndicator: string;
    AdmittingDoctor: string;
    PatientType: string;
    VisitNumber: string;
    FinancialClass: string;
    ChargePriceIndicator: string;
    CourtesyCode: string;
    CreditRating: string;
    ContractCode: string;
    ContractEffDate: string;
    ContractAmount: string;
    ContractPeriod: string;
    InterestCode: string;
    BadDebtCode: string;
    BadDebtDate: string;
    BadDebtAgencyCode: string;
    BadDebtTransferAmt: string;
    BadDebtRecoveryAmt: string;
    DeleteAccIndicator: string;
    DeleteAccDate: string;
    DischargeDisposition: string;
    DischargedLocation: string;
    DietType: string;
    ServicingFacility: string;
    BedStatus: string;
    AccStatus: string;
    PendingLocation: string;
    PriorTemporaryLocation: string;
    AdmitDate: string;
    DischargeDate: string;
    CurrentPatientBalance: string;
    TotalCharges: string;
    TotalAdjustments: string;
    TotalPayments: string;
    AlternateVisitId: string;
    VisitIndicator: string;
    OtherHealthProvider: string;
    PVisit_Status: number;
    PVisit_CreatedBy: number;
    PVisit_CreatedDate: string;
    PVOutBoundFileStatus: number;
    PVOutBoundApproval: number;
    PVOutBoundApprovalBy: number;
    PVOutBoundApprovalOn: string;
    Wing: number;
    Physician_Id: number;
    ApprovalPVisit_Id:number;
    DischargeTime:string;
}
export class NewResidentInfo
{
    DemographicDetails:ResidentDemographicMaster;
    VisitInfoDetails:AdmitvisitInfo;
    ResidentUniqueId:string;

}
export class AdmitvisitInfo {
    PVisit_Id: number;
    Patient_Id: number;
    PatientClass: string;
    NursingStationId: string;
    Room: string;
    Bed: string;
    FacilityId: string;
    Floor: string;
    AdmissionType: string;
    PreAdmitNumber: string;
    PriorNursingStationId: string;
    PriorRoom: string;
    PriorBed: string;
    PriorFacilityId: string;
    PriorFloor: string;
    PrimaryPhysicianNPI: string;
    PrimaryPhysicianLName: string;
    PrimaryPhysicianFName: string;
    ReferringDoctor: string;
    ConsultingDoctor: string;
    HospitalService: string;
    TemporaryLocation: string;
    PreAdmitTestIndicator: string;
    ReAdmissionIndicator: string;
    AdmitSource: string;
    AmbulatoryStatus: string;
    VIPIndicator: string;
    AdmittingDoctor: string;
    PatientType: string;
    VisitNumber: string;
    FinancialClass: string;
    ChargePriceIndicator: string;
    CourtesyCode: string;
    CreditRating: string;
    ContractCode: string;
    ContractEffDate: string;
    ContractAmount: string;
    ContractPeriod: string;
    InterestCode: string;
    BadDebtCode: string;
    BadDebtDate: string;
    BadDebtAgencyCode: string;
    BadDebtTransferAmt: string;
    BadDebtRecoveryAmt: string;
    DeleteAccIndicator: string;
    DeleteAccDate: string;
    DischargeDisposition: string;
    DischargedLocation: string;
    DietType: string;
    ServicingFacility: string;
    BedStatus: string;
    AccStatus: string;
    PendingLocation: string;
    PriorTemporaryLocation: string;
    AdmitDate: string;
    DischargeDate: string;
    CurrentPatientBalance: string;
    TotalCharges: string;
    TotalAdjustments: string;
    TotalPayments: string;
    AlternateVisitId: string;
    VisitIndicator: string;
    OtherHealthProvider: string;
    PVisit_Status: number;
    PVisit_CreatedBy: number;
    PVisit_CreatedDate: string;
    PVOutBoundFileStatus: number;
    PVOutBoundApproval: number;
    PVOutBoundApprovalBy: number;
    PVOutBoundApprovalOn: string;
    Wing: number;
    Physician_Id: number;
    DischargeTime:string;
}

export class AdmitInfo {
    PVisit_Id: number;
    Patient_Id: number;
    Room: string;
    Bed: string;
    Floor: string;
    Wing: number;
}
export class LiteralOdersData {
    POrder_Id: number;
    Patient_Id: number;
    OrderControl: string;
    PlacerOrderNumber: string;
    FacilityId: string;
    PatientId: string;
    Room: string;
    OrderTypeID: number;
    PlacerGroupNumber: string;
    OrderStatus: string;
    ResponseFlag: string;
    QuantityTiming: string;
    Parent: string;
    TransactionDate: string;
    EnteredBy: string;
    EPharmacistLName: string;
    EPharmacistFName: string;
    VerifiedBy: string;
    VPharmacistLName: string;
    VPharmacistFName: string;
    VEffectivedate: string;
    OrderingPhysicianNPI: string;
    OPhysicianLname: string;
    OPhysicianFname: string;
    EntererLocation: string;
    CallBackPhoneNumber: string;
    OrderEffectiveDate: string;
    OrderControlCodeReason: string;
    EnteringOrganisation: string;
    EnteringDevice: string;
    AltCodingSystem: string;
    AdvBeneficiaryNoticeCode: string;
    OrderingFacilityName: string;
    OrderingFacilityAddress1: string;
    OrderingFacilityAddress2: string;
    OrderingFacilityCity: string;
    OrderingFacilityState: string;
    OrderingFacilityZip: string;
    OrderingFacilityPhone: string;
    OrderingPhysicianAddress1: string;
    OrderingPhysicianAddress2: string;
    OrderingPhysicianCity: string;
    OrderingPhysicianState: string;
    OrderingProviderZip: string;
    OrderStatusModifier: string;
    AdvBeneficiaryNoticeOverrideReason: string;
    ExpectedAvailabilityDate: string;
    ConfidentialityCode: string;
    OrderType: string;
    EntererAuthorizationMode: string;
    POrder_Status: number;
    POrder_CreatedBy: number;
    POrder_CreatedDate: string;
    POOutBoundFileStatus: number;
    POOutBoundApproval: number;
    POOutBoundApprovalBy: number;
    POOutBoundApprovalOn: string;
    AlertText: string;
    MaxPerdays: number;
    OrderStockFlag: number;
    PRNFlag: number;
    SelfAdministeredFlag: number;
    TreatmentFlag: number;
    Maysubstitute: number;
    OrderingPhysicianID: number;
    InsulinComments: string;
}
export class ResidentMedications {
    PTreatment_Id: number;
    POrder_Id: number;
    ReqGiveCodeIdentifier: string;
    RequestedGiveCode: string;
    RequestedGiveAmtMin: string;
    RequestedGiveAmtMax: string;
    RequestedGiveUnits: string;
    RequestedDosageForm: string;
    ProvidersTreatmentInstructions: string;
    ProvidersAdministrationInstructions: string;
    DeliverToLocation: string;
    AllowSubstitutions: string;
    RequestedDispenseCode: string;
    RequestedDispenseAmount: string;
    RequestedDispenseUnits: string;
    NumberOfRefills: string;
    OrderingProviderDEANumber: string;
    TreatmentSupplierVerifierID: string;
    NeedsHumanReview: string;
    RequestedGivePer: string;
    RequestedGiveStrength: string;
    RequestedGiveStrengthUnits: string;
    IndicationIdentifier: string;
    IndicationText: string;
    IndicationCodingSystem: string;
    AIndicationIdentifier: string;
    AIndicationText: string;
    AIndicationCodingSystem: string;
    RequestedGiveRateAmount: string;
    RequestedGiveRateUnits: string;
    TotalDailyDose: string;
    SupplementaryCode: string;
    RequestedDrugStrengthVol: string;
    RequestedDrugStrengthVolUnits: string;
    PharmacyOrderType: string;
    DispensingInterval: string;
    PTreatment_Status: number;
    PTreatment_CreatedBy: number;
    PTreatment_CreatedDate: string;
    PTIOutBoundFileStatus: number;
    PTIOutBoundApproval: number;
    PTIOutBoundApprovalBy: number;
    PTIOutBoundApprovalOn: string;
}
export class ResidentsCount {
    Admit: number;
    Readmit: number;
    Inactive: number;
    Transfer: number;
    Discharge: number;
}
export class FolderNames {
    FolderID: number;
    FolderName: string;
    FolderParentID: number;
    FolderLocation: string;
    Folder_Status: number;
    Folder_CreatedBy: number;
    Folder_CreatedDate: string;
}
export class ColorCode{
   ColourType_Id:number;
   Patient_Id:number;
   PatientTypeId:string;
   PatientType_Id:number;
   ColourType_Status:number;
   ColourType_CreatedBy:number;
   ColourType_CreatedOn:string;
}
