//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LTCPro.ServiceLayer.WebReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSenderSoap", Namespace="http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?")]
    public partial class WebServiceSender : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportInboundFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecievingMessageStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceSender() {
            this.Url = global::LTCPro.ServiceLayer.Properties.Settings.Default.ServiceLayer_WebReference_WebServiceSender;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMessagesCompletedEventHandler SendMessagesCompleted;
        
        /// <remarks/>
        public event ReceiveMessageCompletedEventHandler ReceiveMessageCompleted;
        
        /// <remarks/>
        public event ImportInboundFilesCompletedEventHandler ImportInboundFilesCompleted;
        
        /// <remarks/>
        public event RecievingMessageStatusCompletedEventHandler RecievingMessageStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?/SendMessages", RequestNamespace="http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?", ResponseNamespace="http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMessages() {
            object[] results = this.Invoke("SendMessages", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessagesAsync() {
            this.SendMessagesAsync(null);
        }
        
        /// <remarks/>
        public void SendMessagesAsync(object userState) {
            if ((this.SendMessagesOperationCompleted == null)) {
                this.SendMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessagesOperationCompleted);
            }
            this.InvokeAsync("SendMessages", new object[0], this.SendMessagesOperationCompleted, userState);
        }
        
        private void OnSendMessagesOperationCompleted(object arg) {
            if ((this.SendMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessagesCompleted(this, new SendMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?/ReceiveMessage", RequestNamespace="http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?", ResponseNamespace="http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReceiveMessage() {
            object[] results = this.Invoke("ReceiveMessage", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync() {
            this.ReceiveMessageAsync(null);
        }
        
        /// <remarks/>
        public void ReceiveMessageAsync(object userState) {
            if ((this.ReceiveMessageOperationCompleted == null)) {
                this.ReceiveMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveMessageOperationCompleted);
            }
            this.InvokeAsync("ReceiveMessage", new object[0], this.ReceiveMessageOperationCompleted, userState);
        }
        
        private void OnReceiveMessageOperationCompleted(object arg) {
            if ((this.ReceiveMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveMessageCompleted(this, new ReceiveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?/ImportInboundFiles", RequestNamespace="http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?", ResponseNamespace="http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ImportInboundFiles() {
            this.Invoke("ImportInboundFiles", new object[0]);
        }
        
        /// <remarks/>
        public void ImportInboundFilesAsync() {
            this.ImportInboundFilesAsync(null);
        }
        
        /// <remarks/>
        public void ImportInboundFilesAsync(object userState) {
            if ((this.ImportInboundFilesOperationCompleted == null)) {
                this.ImportInboundFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportInboundFilesOperationCompleted);
            }
            this.InvokeAsync("ImportInboundFiles", new object[0], this.ImportInboundFilesOperationCompleted, userState);
        }
        
        private void OnImportInboundFilesOperationCompleted(object arg) {
            if ((this.ImportInboundFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportInboundFilesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?/RecievingMessageStatus", RequestNamespace="http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?", ResponseNamespace="http://100.8.37.102/hllistenerauth/WebServiceSender.asmx?", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecievingMessageStatus(int Port) {
            object[] results = this.Invoke("RecievingMessageStatus", new object[] {
                        Port});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecievingMessageStatusAsync(int Port) {
            this.RecievingMessageStatusAsync(Port, null);
        }
        
        /// <remarks/>
        public void RecievingMessageStatusAsync(int Port, object userState) {
            if ((this.RecievingMessageStatusOperationCompleted == null)) {
                this.RecievingMessageStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecievingMessageStatusOperationCompleted);
            }
            this.InvokeAsync("RecievingMessageStatus", new object[] {
                        Port}, this.RecievingMessageStatusOperationCompleted, userState);
        }
        
        private void OnRecievingMessageStatusOperationCompleted(object arg) {
            if ((this.RecievingMessageStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecievingMessageStatusCompleted(this, new RecievingMessageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void SendMessagesCompletedEventHandler(object sender, SendMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ReceiveMessageCompletedEventHandler(object sender, ReceiveMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ImportInboundFilesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void RecievingMessageStatusCompletedEventHandler(object sender, RecievingMessageStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecievingMessageStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecievingMessageStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591